# MediKiosk — the three commands in the brief, plus the ones they depend on.
#
#   make dev      the whole system on this machine, no Google account
#   make test     the suite that gates a deploy
#   make deploy   build, migrate, then shift traffic — in that order
#
# Migrations are their own target and always run before the deploy that needs
# them. They are never a side effect of a container starting: see
# backend/infra-entrypoint.sh for why.

SHELL := /bin/bash
.DEFAULT_GOAL := help

BACKEND := backend
COMPOSE := docker compose

# Prefer the project virtualenv if there is one, so `make test` works from a
# fresh shell without anyone having remembered to activate it. Falls back to
# whatever `python` is on PATH, which is what CI has.
VENV_BIN := $(BACKEND)/.venv/bin
PY       := $(if $(wildcard $(VENV_BIN)/python),$(abspath $(VENV_BIN))/python,python)
RUFF     := $(if $(wildcard $(VENV_BIN)/ruff),$(abspath $(VENV_BIN))/ruff,ruff)
MYPY     := $(if $(wildcard $(VENV_BIN)/mypy),$(abspath $(VENV_BIN))/mypy,mypy)
ALEMBIC  := $(if $(wildcard $(VENV_BIN)/alembic),$(abspath $(VENV_BIN))/alembic,alembic)

# Overridable on the command line: `make deploy PROJECT_ID=... REGION=...`
PROJECT_ID ?= $(shell gcloud config get-value project 2>/dev/null)
REGION     ?= asia-south1

.PHONY: help
help:  ## Show this list
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# --- local ------------------------------------------------------------------

.PHONY: dev
dev: .env  ## Bring up the full local stack (postgres, migrate, seed, api)
	$(COMPOSE) up --build

.PHONY: dev-detached
dev-detached: .env  ## Same, in the background
	$(COMPOSE) up --build -d

.PHONY: down
down:  ## Stop the stack, keeping the data
	$(COMPOSE) down

.PHONY: clean
clean:  ## Stop the stack and delete its volumes. Destroys the local database.
	$(COMPOSE) down -v

.PHONY: logs
logs:  ## Follow the API logs
	$(COMPOSE) logs -f api

.env:
	@echo "No .env found. Copy .env.example to .env and set POSTGRES_PASSWORD" >&2
	@echo "and KIOSK_TOKENS — the stack refuses to start without them." >&2
	@exit 1

# --- checks -----------------------------------------------------------------

.PHONY: test
test:  ## The suite that gates a deploy. Offline; no network marker.
	cd $(BACKEND) && $(PY) -m pytest -q -m "not network"

.PHONY: test-all
test-all:  ## Everything, including the FHIR validation against the published validator
	cd $(BACKEND) && $(PY) -m pytest -q

.PHONY: lint
lint:  ## ruff
	cd $(BACKEND) && $(RUFF) check app tests

.PHONY: fmt
fmt:  ## ruff, fixing what it can
	cd $(BACKEND) && $(RUFF) check --fix app tests && $(RUFF) format app tests

.PHONY: typecheck
typecheck:  ## mypy
	cd $(BACKEND) && $(MYPY) app

.PHONY: check
check: lint typecheck test  ## Everything a deploy requires

# --- database ---------------------------------------------------------------

.PHONY: migrate
migrate:  ## alembic upgrade head against $$DATABASE_URL
	cd $(BACKEND) && $(ALEMBIC) upgrade head

.PHONY: revision
revision:  ## New autogenerated migration: make revision m="add x"
	@test -n "$(m)" || { echo 'usage: make revision m="what changed"' >&2; exit 1; }
	cd $(BACKEND) && $(ALEMBIC) revision --autogenerate -m "$(m)"

.PHONY: seed
seed:  ## Seed the demo facility and the terminology tables. Idempotent.
	cd $(BACKEND) && $(PY) scripts/seed.py

# --- cloud ------------------------------------------------------------------

.PHONY: provision
provision:  ## Create the GCP resources. Idempotent; safe to re-run.
	PROJECT_ID=$(PROJECT_ID) REGION=$(REGION) infra/gcp/00-provision.sh

.PHONY: build-image
build-image:  ## Build and push the image with Cloud Build
	PROJECT_ID=$(PROJECT_ID) REGION=$(REGION) infra/gcp/30-build.sh

.PHONY: migrate-cloud
migrate-cloud: ## Run migrations against Cloud SQL as a one-shot job, pre-deploy
	PROJECT_ID=$(PROJECT_ID) REGION=$(REGION) infra/gcp/35-migrate.sh

.PHONY: deploy
deploy: check build-image migrate-cloud  ## Test, build, migrate, then deploy both services
	PROJECT_ID=$(PROJECT_ID) REGION=$(REGION) infra/gcp/40-deploy.sh
