"""Emit the questioning agent's localization and vocabulary content.

    ./.venv/bin/python scripts/build_questioning_content.py

Writes `clinical/questioning/localization/questions_<lang>.json` and
`clinical/questioning/vocabulary/<lang>.yaml` from the nine-language tables in
`scripts/questioning_content/`.

**Why a generator rather than eighteen hand-written files.** Nine translations
of the same question have to mean the same thing, and the only way to keep them
meaning the same thing is to see them together. Nine files drift apart the first
time somebody edits one; one table with nine columns does not. The repository
already does this for the OCR fixtures.

The generated files are committed, so nothing at runtime depends on this script
having been run — it is the source, not a build step.

It fails rather than emitting a hole: a question with no text in one language, a
row with the wrong number of entries, or an English string sitting in another
language's column all stop the build here rather than in front of a patient.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml  # noqa: E402

from app.questioning_agent.knowledge.information_schema import SlotRegistry  # noqa: E402
from app.questioning_agent.knowledge.questions import QuestionBank  # noqa: E402
from app.questioning_agent.localization.languages import LANGUAGES  # noqa: E402
from questioning_content.options import OPTIONS  # noqa: E402
from questioning_content.questions import QUESTIONS  # noqa: E402
from questioning_content.questions_domains import (  # noqa: E402
    AYUSH_QUESTIONS,
    DOMAIN_QUESTIONS,
)
from questioning_content.vocabulary import VOCABULARY  # noqa: E402

CONTENT = Path(__file__).resolve().parent.parent.parent / "clinical" / "questioning"

ALL_QUESTIONS = {**QUESTIONS, **DOMAIN_QUESTIONS, **AYUSH_QUESTIONS}


def main() -> int:
    slots = SlotRegistry.load(CONTENT)
    bank = QuestionBank.load(CONTENT, slots)

    needed_questions = {q.id for q in bank.all}
    needed_options: set[str] = {d.id for d in slots.domains}
    for question in bank.all:
        needed_options |= set(question.options)
    for slot in slots.all:
        needed_options |= set(slot.allowed_values)

    problems: list[str] = []

    # Every row is nine wide, and none of them is empty.
    for table, name in ((ALL_QUESTIONS, "question"), (OPTIONS, "option")):
        for key, row in table.items():
            if len(row) != len(LANGUAGES):
                problems.append(
                    f"{name} {key!r} has {len(row)} entries, expected {len(LANGUAGES)}"
                )
            for language, text in zip(LANGUAGES, row, strict=False):
                if not text or not text.strip():
                    problems.append(f"{name} {key!r} has no text for {language}")

    missing_q = sorted(needed_questions - set(ALL_QUESTIONS))
    missing_o = sorted(needed_options - set(OPTIONS))
    problems.extend(f"no text for question {q!r}" for q in missing_q)
    problems.extend(f"no text for option {o!r}" for o in missing_o)

    extra_q = sorted(set(ALL_QUESTIONS) - needed_questions)
    extra_o = sorted(set(OPTIONS) - needed_options)
    problems.extend(f"text for question {q!r}, which no bank defines" for q in extra_q)
    problems.extend(f"text for option {o!r}, which nothing offers" for o in extra_o)

    if problems:
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(f"\n{len(problems)} problems; nothing written.", file=sys.stderr)
        return 1

    (CONTENT / "localization").mkdir(parents=True, exist_ok=True)
    (CONTENT / "vocabulary").mkdir(parents=True, exist_ok=True)

    for index, language in enumerate(LANGUAGES):
        payload = {
            "language": language,
            "questions": {k: v[index] for k, v in sorted(ALL_QUESTIONS.items())},
            "options": {k: v[index] for k, v in sorted(OPTIONS.items())},
        }
        path = CONTENT / "localization" / f"questions_{language}.json"
        path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

        vocabulary = {"language": language, **VOCABULARY[language]}
        vocabulary_path = CONTENT / "vocabulary" / f"{language}.yaml"
        vocabulary_path.write_text(
            "# Generated by scripts/build_questioning_content.py — edit the table\n"
            "# there, not this file. See that script for why.\n"
            + yaml.safe_dump(vocabulary, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )

    print(
        f"Wrote {len(LANGUAGES)} question banks "
        f"({len(ALL_QUESTIONS)} questions, {len(OPTIONS)} options) "
        f"and {len(LANGUAGES)} vocabularies."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
