"""Generate docs/CLINICAL_REVIEW_QUEUE.md from the content itself.

    uv run python scripts/review_queue.py

The file is generated rather than hand-maintained because a hand-maintained list
of "things a clinician still needs to look at" drifts out of date immediately,
and this one is the agenda for the AIIA mentor session.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from app.core.config import get_settings
from app.core.content import load_clinical_content

OUTPUT = Path(__file__).resolve().parents[2] / "docs" / "CLINICAL_REVIEW_QUEUE.md"

HEADER = """# Clinical review queue

**Generated by `scripts/review_queue.py` — do not edit by hand.**

Everything below was authored by an engineer rather than by a clinician, or
carries a `clinical_source` that has not yet been reviewed. This is the agenda
for the AIIA mentor session, not a list of known defects: each item is a
question about clinical content, and the answer belongs in the YAML.

Two things worth stating plainly before the session:

- Nothing here is a diagnostic rule. The red-flag criteria decide when a human
  is asked to look, never what is wrong with the patient.
- Every item can be changed by editing `clinical/**` alone. None of it requires
  a code change, which is the point of keeping the content out of Python.
"""


def main() -> None:
    content = load_clinical_content(get_settings())
    items = content.review_queue()

    lines = [HEADER, ""]
    lines.append(f"_Generated {datetime.now(UTC).date().isoformat()} — {len(items)} items._")
    lines.append("")

    concepts = [i for i in items if i.startswith("concept ")]
    fields = [i for i in items if i.startswith("pathway ")]
    rules = [i for i in items if i.startswith("red-flag rule ") and "unreviewed" not in i]
    sources = [i for i in items if "unreviewed clinical_source" in i]

    for title, group, note in (
        (
            "Concepts",
            concepts,
            "Wording and clinical meaning need a Vaidya's confirmation.",
        ),
        (
            "Pathway and screen fields",
            fields,
            "Is this the right question, in the right words, at the right point?",
        ),
        (
            "Red-flag rules",
            rules,
            "Are the criteria right, and is the severity right? Recall matters more "
            "than precision here — over-alerting is tuned down later, a missed "
            "emergency is not recoverable.",
        ),
        (
            "Rules awaiting a named clinical source",
            sources,
            "Every rule must name the guideline or the clinician who approved it. "
            "These currently say 'pending AIIA mentor review'.",
        ),
    ):
        lines.append(f"## {title} ({len(group)})")
        lines.append("")
        lines.append(note)
        lines.append("")
        if group:
            lines.extend(f"- [ ] {item}" for item in group)
        else:
            lines.append("_Nothing outstanding._")
        lines.append("")

    lines.append("## Terminology seeds")
    lines.append("")
    lines.append(
        "`clinical/terminology/*_seed.yaml` contain development placeholders shaped "
        "like real NAMASTE and ICD-11 codes. They must be replaced with the licensed "
        "releases before any clinical use. The loader ingests a full release into the "
        "same tables, so this is a data swap rather than a code change."
    )
    lines.append("")
    lines.append(
        "`clinical/terminology/conceptmap.yaml` records where a NAMASTE concept and a "
        "biomedical code are *correlated*, not equivalent — Madhumeha and type 2 "
        "diabetes mellitus overlap but are not the same entity. Every `equivalence` "
        "value needs a clinician's judgement."
    )
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(items)} items)")


if __name__ == "__main__":
    main()
