"""Patient app sign-in: OTP challenges and patient sessions.

Both tables sit outside the tenant guard, because a person signs into the
app before choosing a hospital. Neither holds a plaintext phone number, a
code or a usable token — the phone is a peppered HMAC and the rest are
hashes — which is what makes that exemption defensible rather than merely
convenient. See app/models/clinical.py and 2/3 section 7.1.
"""


from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models.base

revision = "0002_patient_app_auth"
down_revision = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phone_ref', sa.String(length=128), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    op.create_index(op.f('ix_otp_challenges_phone_ref'), 'otp_challenges', ['phone_ref'], unique=False)
    op.create_table('patient_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('phone_ref', sa.String(length=128), nullable=False),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_sessions'))
    )
    op.create_index(op.f('ix_patient_sessions_phone_ref'), 'patient_sessions', ['phone_ref'], unique=False)
    op.create_index(op.f('ix_patient_sessions_token_hash'), 'patient_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_sessions_token_hash'), table_name='patient_sessions')
    op.drop_index(op.f('ix_patient_sessions_phone_ref'), table_name='patient_sessions')
    op.drop_table('patient_sessions')
    op.drop_index(op.f('ix_otp_challenges_phone_ref'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
