"""initial schema

Revision ID: 6f50500eabf8
Revises: 
Create Date: 2026-09-01 00:45:32.464314
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6f50500eabf8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('consent_artefacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('notice_hash', sa.String(length=64), nullable=False),
    sa.Column('notice_text', sa.Text(), nullable=False),
    sa.Column('audio_asset_id', sa.String(length=128), nullable=True),
    sa.Column('granted_purposes', sa.JSON(), nullable=False),
    sa.Column('refused_purposes', sa.JSON(), nullable=False),
    sa.Column('granting_party', sa.String(length=32), nullable=False),
    sa.Column('granting_party_name', sa.String(length=256), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_artefacts'))
    )
    op.create_index(op.f('ix_consent_artefacts_intake_id'), 'consent_artefacts', ['intake_id'], unique=False)
    op.create_index(op.f('ix_consent_artefacts_patient_id'), 'consent_artefacts', ['patient_id'], unique=False)
    op.create_table('departments',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('facility', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_departments'))
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'endpoint', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('external_mrn', sa.String(length=128), nullable=True),
    sa.Column('abha_address', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('external_mrn', name='uq_patients_external_mrn')
    )
    op.create_index(op.f('ix_patients_abha_address'), 'patients', ['abha_address'], unique=False)
    op.create_index(op.f('ix_patients_external_mrn'), 'patients', ['external_mrn'], unique=False)
    op.create_table('terminology_concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=256), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('discipline', sa.String(length=32), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminology_concepts')),
    sa.UniqueConstraint('system', 'code', name='uq_terminology_concepts_system_code')
    )
    op.create_index(op.f('ix_terminology_concepts_system'), 'terminology_concepts', ['system'], unique=False)
    op.create_table('terminology_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('target_system', sa.String(length=32), nullable=False),
    sa.Column('target_code', sa.String(length=64), nullable=False),
    sa.Column('equivalence', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminology_mappings')),
    sa.UniqueConstraint('source_system', 'source_code', 'target_system', 'target_code', name='uq_terminology_mappings_source_target')
    )
    op.create_index(op.f('ix_terminology_mappings_source_code'), 'terminology_mappings', ['source_code'], unique=False)
    op.create_index(op.f('ix_terminology_mappings_source_system'), 'terminology_mappings', ['source_system'], unique=False)
    op.create_index(op.f('ix_terminology_mappings_target_system'), 'terminology_mappings', ['target_system'], unique=False)
    op.create_table('intakes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('reporter_role', sa.String(length=32), nullable=False),
    sa.Column('active_pathway', sa.String(length=64), nullable=True),
    sa.Column('active_ros_groups', sa.JSON(), nullable=False),
    sa.Column('ayurveda_enabled', sa.Boolean(), nullable=False),
    sa.Column('declined_concepts', sa.JSON(), nullable=False),
    sa.Column('consent_artefact_id', sa.String(length=64), nullable=True),
    sa.Column('kiosk_id', sa.String(length=64), nullable=True),
    sa.Column('department_code', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_intakes_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intakes'))
    )
    op.create_index(op.f('ix_intakes_consent_artefact_id'), 'intakes', ['consent_artefact_id'], unique=False)
    op.create_index(op.f('ix_intakes_department_code'), 'intakes', ['department_code'], unique=False)
    op.create_index(op.f('ix_intakes_kiosk_id'), 'intakes', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_intakes_last_activity_at'), 'intakes', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_intakes_patient_id'), 'intakes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_intakes_state'), 'intakes', ['state'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department_code', sa.String(length=32), nullable=False),
    sa.Column('service_point', sa.String(length=64), nullable=False),
    sa.Column('assignment_policy', sa.String(length=32), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('schedule_days', sa.JSON(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('priority_classes', sa.JSON(), nullable=False),
    sa.Column('prefer_intake_ready', sa.Boolean(), nullable=False),
    sa.Column('intake_ready_window', sa.Integer(), nullable=False),
    sa.Column('max_overtaken', sa.Integer(), nullable=False),
    sa.Column('recall_after_tokens', sa.Integer(), nullable=False),
    sa.Column('max_recalls', sa.Integer(), nullable=False),
    sa.Column('unserved_policy', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], name=op.f('fk_queues_department_code_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues'))
    )
    op.create_index(op.f('ix_queues_department_code'), 'queues', ['department_code'], unique=False)
    op.create_table('clinical_facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.String(length=128), nullable=False),
    sa.Column('concept_system', sa.String(length=64), nullable=True),
    sa.Column('concept_code', sa.String(length=64), nullable=True),
    sa.Column('concept_display', sa.String(length=256), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('certainty', sa.String(length=32), nullable=False),
    sa.Column('temporality', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('original_expression', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=16), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reported_by', sa.String(length=32), nullable=False),
    sa.Column('patient_confirmed', sa.Boolean(), nullable=False),
    sa.Column('physician_verified', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_clinical_facts_intake_id_intakes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_facts')),
    sa.UniqueConstraint('intake_id', 'seq', name='uq_clinical_facts_intake_id_seq')
    )
    op.create_index(op.f('ix_clinical_facts_concept_id'), 'clinical_facts', ['concept_id'], unique=False)
    op.create_index('ix_clinical_facts_intake_concept', 'clinical_facts', ['intake_id', 'concept_id'], unique=False)
    op.create_index(op.f('ix_clinical_facts_intake_id'), 'clinical_facts', ['intake_id'], unique=False)
    op.create_index(op.f('ix_clinical_facts_section'), 'clinical_facts', ['section'], unique=False)
    op.create_index(op.f('ix_clinical_facts_source_type'), 'clinical_facts', ['source_type'], unique=False)
    op.create_index(op.f('ix_clinical_facts_supersedes'), 'clinical_facts', ['supersedes'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_documents_intake_id_intakes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_intake_id'), 'documents', ['intake_id'], unique=False)
    op.create_table('queue_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('practitioner_id', sa.String(length=64), nullable=True),
    sa.Column('service_point', sa.String(length=64), nullable=True),
    sa.Column('last_issued', sa.Integer(), nullable=False),
    sa.Column('now_serving', sa.String(length=32), nullable=True),
    sa.Column('waiting_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('avg_service_seconds', sa.Float(), nullable=True),
    sa.Column('served_sample', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_into', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_queue_instances_queue_id_queues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_instances')),
    sa.UniqueConstraint('queue_id', 'service_date', 'session', name='uq_queue_instances_queue_date_session')
    )
    op.create_index(op.f('ix_queue_instances_practitioner_id'), 'queue_instances', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_queue_instances_queue_id'), 'queue_instances', ['queue_id'], unique=False)
    op.create_index(op.f('ix_queue_instances_service_date'), 'queue_instances', ['service_date'], unique=False)
    op.create_index(op.f('ix_queue_instances_status'), 'queue_instances', ['status'], unique=False)
    op.create_table('red_flag_alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('clinical_source', sa.String(length=256), nullable=False),
    sa.Column('criteria_description', sa.Text(), nullable=False),
    sa.Column('supporting_fact_ids', sa.JSON(), nullable=False),
    sa.Column('notify', sa.String(length=32), nullable=False),
    sa.Column('priority_hint', sa.String(length=32), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_by', sa.String(length=64), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissal_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_red_flag_alerts_intake_id_intakes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_red_flag_alerts')),
    sa.UniqueConstraint('intake_id', 'rule_id', name='uq_red_flag_alerts_intake_id_rule_id')
    )
    op.create_index(op.f('ix_red_flag_alerts_acknowledged_by'), 'red_flag_alerts', ['acknowledged_by'], unique=False)
    op.create_index(op.f('ix_red_flag_alerts_intake_id'), 'red_flag_alerts', ['intake_id'], unique=False)
    op.create_index(op.f('ix_red_flag_alerts_rule_id'), 'red_flag_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_red_flag_alerts_severity'), 'red_flag_alerts', ['severity'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('intake_id', sa.String(length=64), nullable=False),
    sa.Column('intake_revision', sa.Integer(), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('physician_verified_by', sa.String(length=64), nullable=True),
    sa.Column('physician_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_reports_intake_id_intakes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_intake_id'), 'reports', ['intake_id'], unique=False)
    op.create_index(op.f('ix_reports_physician_verified_by'), 'reports', ['physician_verified_by'], unique=False)
    op.create_index(op.f('ix_reports_service_date'), 'reports', ['service_date'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('token_number', sa.String(length=32), nullable=False),
    sa.Column('token_sequence', sa.Integer(), nullable=False),
    sa.Column('recall_sequence', sa.Integer(), nullable=True),
    sa.Column('priority_class', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('intake_id', sa.String(length=64), nullable=True),
    sa.Column('appointment_slot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('overtaken_count', sa.Integer(), nullable=False),
    sa.Column('wait_credit_seconds', sa.Float(), nullable=False),
    sa.Column('transferred_from', sa.String(length=64), nullable=True),
    sa.Column('transferred_to', sa.String(length=64), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('escalation_alert_id', sa.String(length=64), nullable=True),
    sa.Column('escalation_acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('escalation_escalated_by', sa.String(length=64), nullable=True),
    sa.Column('escalation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['queue_instances.id'], name=op.f('fk_tickets_instance_id_queue_instances')),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_tickets_queue_id_queues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('instance_id', 'token_number', name='uq_tickets_instance_token')
    )
    op.create_index(op.f('ix_tickets_instance_id'), 'tickets', ['instance_id'], unique=False)
    op.create_index('ix_tickets_instance_state_priority', 'tickets', ['instance_id', 'state', 'priority_class'], unique=False)
    op.create_index(op.f('ix_tickets_intake_id'), 'tickets', ['intake_id'], unique=False)
    op.create_index(op.f('ix_tickets_patient_id'), 'tickets', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority_class'), 'tickets', ['priority_class'], unique=False)
    op.create_index(op.f('ix_tickets_queue_id'), 'tickets', ['queue_id'], unique=False)
    op.create_index(op.f('ix_tickets_state'), 'tickets', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_state'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_queue_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority_class'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_patient_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_intake_id'), table_name='tickets')
    op.drop_index('ix_tickets_instance_state_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_instance_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_reports_service_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_physician_verified_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_intake_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_red_flag_alerts_severity'), table_name='red_flag_alerts')
    op.drop_index(op.f('ix_red_flag_alerts_rule_id'), table_name='red_flag_alerts')
    op.drop_index(op.f('ix_red_flag_alerts_intake_id'), table_name='red_flag_alerts')
    op.drop_index(op.f('ix_red_flag_alerts_acknowledged_by'), table_name='red_flag_alerts')
    op.drop_table('red_flag_alerts')
    op.drop_index(op.f('ix_queue_instances_status'), table_name='queue_instances')
    op.drop_index(op.f('ix_queue_instances_service_date'), table_name='queue_instances')
    op.drop_index(op.f('ix_queue_instances_queue_id'), table_name='queue_instances')
    op.drop_index(op.f('ix_queue_instances_practitioner_id'), table_name='queue_instances')
    op.drop_table('queue_instances')
    op.drop_index(op.f('ix_documents_intake_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_clinical_facts_supersedes'), table_name='clinical_facts')
    op.drop_index(op.f('ix_clinical_facts_source_type'), table_name='clinical_facts')
    op.drop_index(op.f('ix_clinical_facts_section'), table_name='clinical_facts')
    op.drop_index(op.f('ix_clinical_facts_intake_id'), table_name='clinical_facts')
    op.drop_index('ix_clinical_facts_intake_concept', table_name='clinical_facts')
    op.drop_index(op.f('ix_clinical_facts_concept_id'), table_name='clinical_facts')
    op.drop_table('clinical_facts')
    op.drop_index(op.f('ix_queues_department_code'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_intakes_state'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_patient_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_last_activity_at'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_kiosk_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_department_code'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_consent_artefact_id'), table_name='intakes')
    op.drop_table('intakes')
    op.drop_index(op.f('ix_terminology_mappings_target_system'), table_name='terminology_mappings')
    op.drop_index(op.f('ix_terminology_mappings_source_system'), table_name='terminology_mappings')
    op.drop_index(op.f('ix_terminology_mappings_source_code'), table_name='terminology_mappings')
    op.drop_table('terminology_mappings')
    op.drop_index(op.f('ix_terminology_concepts_system'), table_name='terminology_concepts')
    op.drop_table('terminology_concepts')
    op.drop_index(op.f('ix_patients_external_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_abha_address'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('idempotency_keys')
    op.drop_table('departments')
    op.drop_index(op.f('ix_consent_artefacts_patient_id'), table_name='consent_artefacts')
    op.drop_index(op.f('ix_consent_artefacts_intake_id'), table_name='consent_artefacts')
    op.drop_table('consent_artefacts')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
