"""Per-language parsing vocabulary — §24.

**The English parser does not work on Hindi and was never going to.** Hindi
negates at the end of the clause; Tamil marks it on the verb; the numerals are
different glyphs in six of these nine scripts. A single tokeniser with a lookup
table bolted on is an English parser that sometimes gets other languages right,
which is worse than one that admits it cannot — because the failure is silent
and lands in a clinical record.

So every language brings its own cues, and the parsers are generic machinery
over this data.

The synonym lists are the words patients actually use, including English words
in Latin script, because a Hindi speaker typing on an English keyboard writes
"fever" as often as "बुखार" and both have to work.
"""

from __future__ import annotations

from typing import Any

# Shared across every language: Arabic numerals appear in all of them, and so do
# English symptom words typed on a phone keyboard that has no Devanagari.
_LATIN_FALLBACK: dict[str, list[str]] = {
    "fever": ["fever", "temperature", "bukhar"],
    "pain": ["pain", "dard", "ache"],
    "headache": ["headache", "head pain", "sir dard"],
    "respiratory": ["cough", "khansi", "breathless", "breathing"],
    "digestive": ["stomach", "pet", "acidity", "indigestion", "gas"],
    "bowel": ["stool", "motion", "loose motion", "constipation", "latrine"],
    "urinary": ["urine", "peshab", "urination"],
    "skin": ["skin", "rash", "itching"],
    "fatigue": ["weakness", "tired", "kamzori", "fatigue"],
    "sleep": ["sleep", "insomnia", "neend"],
    "joint": ["joint pain", "knee pain", "body pain", "ghutna"],
    "menstrual": ["periods", "menstrual", "mahavari"],
    "mental": ["stress", "tension", "anxiety", "depressed"],
    "bleeding": ["bleeding", "blood", "khoon"],
}

VOCABULARY: dict[str, dict[str, Any]] = {
    # =========================================================================
    "en": {
        "affirm": ["yes", "yeah", "yep", "yup", "ya", "correct", "right", "true", "sure",
                   "definitely", "certainly", "ok", "okay", "haan", "haa"],
        "deny": ["no", "nope", "nah", "not", "none", "never", "negative", "nahi", "nahin",
                 "n", "dont", "didnt", "havent", "hasnt", "isnt", "wasnt", "cant", "wont"],
        "unsure": ["maybe", "perhaps", "possibly", "think", "guess", "unsure", "sometimes",
                   "kind", "sort", "probably", "might"],
        "negation": {
            "cues": ["no", "not", "never", "without", "denies", "dont", "didnt", "havent",
                     "hasnt", "isnt", "wasnt", "nor", "neither", "none", "cant", "wont"],
            "boundaries": ["but", "however", "although", "though", "except", "still", "yet"],
        },
        "numbers": {"zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
                    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11,
                    "twelve": 12, "fifteen": 15, "twenty": 20, "thirty": 30, "forty": 40,
                    "fifty": 50, "hundred": 100, "a couple": 2, "couple": 2, "few": 3,
                    "half": 0.5, "once": 1, "twice": 2, "thrice": 3},
        "duration_units": {"hour": ["hour", "hours", "hrs", "hr"],
                           "day": ["day", "days", "din"],
                           "week": ["week", "weeks", "hafta", "hafte"],
                           "month": ["month", "months", "mahina", "mahine"],
                           "year": ["year", "years", "saal", "yrs"]},
        "temporal": {"today": [0, "day"], "since today": [0, "day"], "yesterday": [1, "day"],
                     "since yesterday": [1, "day"], "day before yesterday": [2, "day"],
                     "last night": [1, "day"], "this morning": [0, "day"],
                     "a few days": [3, "day"], "few days": [3, "day"],
                     "last week": [1, "week"], "since last week": [1, "week"],
                     "a week": [1, "week"], "last month": [1, "month"],
                     "since last month": [1, "month"], "a month": [1, "month"],
                     "last year": [1, "year"], "a year": [1, "year"]},
        "approximate": ["about", "around", "roughly", "approximately", "nearly", "almost",
                        "or so", "a few", "some", "maybe", "close to", "give or take"],
        "severity": {"mild": 3, "slight": 2, "moderate": 5, "bad": 7, "severe": 8,
                     "very bad": 9, "unbearable": 10, "terrible": 9, "worst": 10},
        "symptoms": {
            "fever": ["fever", "temperature", "high temperature", "running a temperature",
                      "running a fever", "feverish", "hot", "bukhar", "pyrexia"],
            "pain": ["pain", "ache", "aching", "hurts", "hurting", "sore", "dard"],
            "headache": ["headache", "head pain", "pain in my head", "migraine", "sir dard"],
            "respiratory": ["cough", "coughing", "breathless", "breathlessness", "short of breath",
                            "wheezing", "chest tightness", "khansi", "sans"],
            "digestive": ["stomach", "tummy", "belly", "indigestion", "acidity", "heartburn",
                          "gas", "bloating", "nausea", "vomiting", "throwing up", "threw up",
                          "puking", "pet dard"],
            "bowel": ["stool", "motion", "loose motion", "loose motions", "diarrhoea", "diarrhea",
                      "constipation", "constipated", "latrine", "toilet", "bowel"],
            "urinary": ["urine", "urination", "peeing", "passing water", "burning urine",
                        "peshab"],
            "skin": ["skin", "rash", "itching", "itchy", "boils", "pimples", "spots"],
            "fatigue": ["weak", "weakness", "tired", "tiredness", "fatigue", "exhausted",
                        "no energy", "kamzori", "thakan"],
            "sleep": ["sleep", "sleepless", "insomnia", "cannot sleep", "neend"],
            "joint": ["joint", "joints", "knee", "knees", "back pain", "body ache", "body pain",
                      "muscle pain", "aching all over", "whole body hurts", "ghutna", "jodon"],
            "menstrual": ["period", "periods", "menstrual", "menses", "cycle", "mahavari"],
            "mental": ["stressed", "stress", "tension", "anxious", "anxiety", "depressed",
                       "low", "sad", "worried", "panic"],
            "bleeding": ["bleeding", "blood", "bled", "khoon"],
        },
        "options": {
            "burning": ["burning", "burn", "jalan", "hot pain"],
            "cramping": ["cramp", "cramping", "cramps", "griping", "marod"],
            "stabbing": ["stabbing", "sharp", "like a knife", "pricking", "needle"],
            "dull_ache": ["dull", "dull ache", "mild ache", "constant ache"],
            "throbbing": ["throbbing", "pounding", "pulsating", "beating"],
            "pressing": ["pressing", "pressure", "heavy", "tight", "squeezing"],
            "shooting": ["shooting", "radiating", "electric"],
            "upper_abdomen": ["upper abdomen", "upper stomach", "epigastric", "above the navel",
                              "right side of my stomach", "left side of my stomach", "upper belly"],
            "lower_abdomen": ["lower abdomen", "lower stomach", "below the navel", "lower belly"],
            "chest": ["chest", "seene", "heart area"],
            "head": ["head", "sir"],
            "back": ["back", "lower back", "spine", "kamar"],
            "neck": ["neck", "gardan"],
            "limb": ["arm", "leg", "hand", "foot", "shoulder", "elbow", "wrist", "ankle"],
            "joint": ["joint", "knee", "elbow", "shoulder"],
            "sudden": ["sudden", "suddenly", "all at once", "out of nowhere", "abruptly"],
            "gradual": ["gradual", "gradually", "slowly", "little by little", "over time"],
            "improving": ["better", "improving", "getting better", "settling", "easing"],
            "worsening": ["worse", "worsening", "getting worse", "increasing", "bad"],
            "unchanged": ["same", "no change", "unchanged", "as before"],
            "fluctuating": ["up and down", "varies", "changes", "on and off"],
            "constant": ["constant", "all the time", "continuous", "always", "non stop"],
            "intermittent": ["comes and goes", "on and off", "intermittent", "now and then",
                             "sometimes"],
            "worse_after_eating": ["worse after eating", "after eating", "after meals",
                                   "after food"],
            "better_after_eating": ["better after eating", "relieved by food", "eating helps"],
            "worse_when_empty": ["empty stomach", "when hungry", "before eating"],
            "dry": ["dry", "dry cough", "no phlegm"],
            "productive": ["phlegm", "sputum", "mucus", "bringing up", "wet cough", "balgam"],
            "yes": ["yes", "yeah", "haan"],
            "no": ["no", "nope", "nahi"],
        },
        "sites": {},
    },
    # =========================================================================
    "hi": {
        "affirm": ["हाँ", "हां", "जी", "जी हाँ", "बिलकुल", "सही", "ठीक", "है", "हूँ",
                   "haan", "haa", "ji", "yes", "ha"],
        "deny": ["नहीं", "ना", "नही", "कभी नहीं", "बिलकुल नहीं", "नाही",
                 "nahi", "nahin", "na", "no"],
        "unsure": ["शायद", "पता नहीं", "कह नहीं सकते", "हो सकता है", "थोड़ा", "कभी-कभी",
                   "shayad", "maybe", "pata nahi"],
        "negation": {
            "cues": ["नहीं", "ना", "नही", "बिना", "कभी", "नाही", "nahi", "nahin", "na", "no", "not"],
            "boundaries": ["लेकिन", "पर", "मगर", "फिर", "हालांकि", "but", "lekin"],
            # Hindi puts its negation before the verb at the end of the clause,
            # so "बुखार नहीं है" has the cue *after* the symptom. Scanning only
            # backwards would read that as an affirmation.
            "sentence_final": True,
        },
        "numbers": {"एक": 1, "दो": 2, "तीन": 3, "चार": 4, "पाँच": 5, "पांच": 5, "छह": 6,
                    "सात": 7, "आठ": 8, "नौ": 9, "दस": 10, "पंद्रह": 15, "बीस": 20,
                    "आधा": 0.5, "एक-दो": 1, "दो-तीन": 2, "कुछ": 3,
                    "ek": 1, "do": 2, "teen": 3, "char": 4, "panch": 5},
        "duration_units": {"hour": ["घंटा", "घंटे", "घण्टे", "ghanta", "hour", "hours"],
                           "day": ["दिन", "din", "day", "days"],
                           "week": ["हफ्ता", "हफ्ते", "सप्ताह", "hafta", "hafte", "week", "weeks"],
                           "month": ["महीना", "महीने", "माह", "mahina", "month", "months"],
                           "year": ["साल", "वर्ष", "बरस", "saal", "year", "years"]},
        "temporal": {"आज": [0, "day"], "कल": [1, "day"], "कल से": [1, "day"],
                     "परसों": [2, "day"], "कल रात": [1, "day"], "आज सुबह": [0, "day"],
                     "कुछ दिन": [3, "day"], "कुछ दिनों": [3, "day"],
                     "पिछले हफ्ते": [1, "week"], "एक हफ्ते": [1, "week"],
                     "पिछले महीने": [1, "month"], "एक महीने": [1, "month"],
                     "पिछले साल": [1, "year"], "एक साल": [1, "year"]},
        "approximate": ["लगभग", "करीब", "तकरीबन", "के आसपास", "कुछ", "शायद",
                        "about", "around", "lagbhag", "kareeb"],
        "severity": {"हल्का": 3, "थोड़ा": 2, "मध्यम": 5, "तेज़": 7, "तेज": 7,
                     "बहुत तेज़": 9, "असहनीय": 10, "बहुत ज़्यादा": 9},
        "symptoms": {
            "fever": ["बुखार", "ज्वर", "तापमान", "गर्मी", "बदन गर्म", "bukhar", "fever"],
            "pain": ["दर्द", "पीड़ा", "तकलीफ़", "दुखता", "dard", "pain"],
            "headache": ["सिरदर्द", "सिर दर्द", "सिर में दर्द", "माइग्रेन", "sir dard"],
            "respiratory": ["खाँसी", "खांसी", "साँस", "सांस फूलना", "दमा", "सीने में जकड़न",
                            "khansi", "cough"],
            "digestive": ["पेट", "पेट दर्द", "गैस", "अपच", "जलन", "एसिडिटी", "उल्टी",
                          "जी मिचलाना", "मतली", "pet dard", "acidity"],
            "bowel": ["शौच", "दस्त", "पतले दस्त", "कब्ज़", "कब्ज", "मल", "टट्टी",
                      "loose motion", "constipation"],
            "urinary": ["पेशाब", "मूत्र", "पेशाब में जलन", "peshab", "urine"],
            "skin": ["त्वचा", "चमड़ी", "खुजली", "चकत्ते", "दाने", "फोड़े", "skin", "rash"],
            "fatigue": ["कमज़ोरी", "कमजोरी", "थकान", "थका", "शक्ति नहीं", "kamzori", "thakan"],
            "sleep": ["नींद", "नींद नहीं आती", "अनिद्रा", "neend", "sleep"],
            "joint": ["जोड़", "जोड़ों", "घुटना", "घुटने", "कमर दर्द", "बदन दर्द", "शरीर दर्द",
                      "ghutna", "jodon", "body pain"],
            "menstrual": ["माहवारी", "पीरियड", "मासिक", "महावारी", "mahavari", "periods"],
            "mental": ["तनाव", "चिंता", "घबराहट", "उदासी", "मन नहीं लगता", "डिप्रेशन",
                       "tension", "stress"],
            "bleeding": ["खून", "रक्त", "खून आना", "रक्तस्राव", "khoon", "blood"],
        },
        "options": {
            "burning": ["जलन", "जलता", "जल रहा", "jalan", "burning"],
            "cramping": ["मरोड़", "ऐंठन", "marod", "cramp"],
            "stabbing": ["चुभन", "चुभता", "तेज़ चुभन", "chubhan"],
            "dull_ache": ["हल्का दर्द", "मंद दर्द", "हल्का सा दर्द"],
            "throbbing": ["टीस", "धड़कता", "टीस मारता"],
            "pressing": ["दबाव", "भारीपन", "जकड़न", "दबता"],
            "shooting": ["झटका", "फैलता दर्द"],
            "upper_abdomen": ["पेट का ऊपरी हिस्सा", "ऊपरी पेट", "नाभि के ऊपर", "दाहिनी ओर पेट"],
            "lower_abdomen": ["पेट का निचला हिस्सा", "निचला पेट", "नाभि के नीचे"],
            "chest": ["सीना", "सीने", "छाती", "seene"],
            "head": ["सिर", "माथा", "sir"],
            "back": ["पीठ", "कमर", "peeth", "kamar"],
            "neck": ["गर्दन", "gardan"],
            "limb": ["हाथ", "पैर", "कंधा", "कोहनी"],
            "sudden": ["अचानक", "एकदम", "achanak"],
            "gradual": ["धीरे-धीरे", "धीरे धीरे", "आहिस्ता", "dheere"],
            "improving": ["बेहतर", "आराम", "कम हो रहा", "ठीक हो रहा"],
            "worsening": ["बिगड़", "बढ़ रहा", "ज़्यादा हो रहा", "खराब"],
            "unchanged": ["वैसा ही", "कोई बदलाव नहीं", "same"],
            "fluctuating": ["कभी कम कभी ज़्यादा", "ऊपर नीचे"],
            "constant": ["हर समय", "लगातार", "हमेशा"],
            "intermittent": ["आता जाता", "कभी-कभी", "रुक रुक कर"],
            "worse_after_eating": ["खाने के बाद", "भोजन के बाद"],
            "better_after_eating": ["खाने से आराम", "खाने के बाद ठीक"],
            "worse_when_empty": ["खाली पेट", "भूख लगने पर"],
            "dry": ["सूखी", "सूखी खाँसी"],
            "productive": ["बलगम", "कफ", "balgam"],
            "yes": ["हाँ", "हां", "जी", "haan"],
            "no": ["नहीं", "ना", "nahi"],
        },
        "sites": {},
    },
}


# The remaining seven. Structure identical; the words are each language's own.
_MORE: dict[str, dict[str, Any]] = {
    "bn": {
        "affirm": ["হ্যাঁ", "হ্যা", "জি", "ঠিক", "সঠিক", "আছে", "hyan", "yes", "ha"],
        "deny": ["না", "নেই", "নয়", "কখনো না", "নাই", "na", "nei", "no"],
        "unsure": ["হয়তো", "জানি না", "বলতে পারি না", "মাঝে মাঝে", "hoyto", "maybe"],
        "negation": {"cues": ["না", "নেই", "নয়", "নাই", "ছাড়া", "na", "nei", "no", "not"],
                     "boundaries": ["কিন্তু", "তবে", "যদিও", "but", "kintu"],
                     "sentence_final": True},
        "numbers": {"এক": 1, "দুই": 2, "তিন": 3, "চার": 4, "পাঁচ": 5, "ছয়": 6, "সাত": 7,
                    "আট": 8, "নয়": 9, "দশ": 10, "অর্ধেক": 0.5, "কয়েক": 3,
                    "ek": 1, "dui": 2, "tin": 3},
        "duration_units": {"hour": ["ঘণ্টা", "ঘন্টা", "hour", "hours"],
                           "day": ["দিন", "din", "day", "days"],
                           "week": ["সপ্তাহ", "হপ্তা", "week", "weeks"],
                           "month": ["মাস", "mash", "month", "months"],
                           "year": ["বছর", "bochor", "year", "years"]},
        "temporal": {"আজ": [0, "day"], "গতকাল": [1, "day"], "কাল": [1, "day"],
                     "গত রাতে": [1, "day"], "কয়েক দিন": [3, "day"],
                     "গত সপ্তাহে": [1, "week"], "এক সপ্তাহ": [1, "week"],
                     "গত মাসে": [1, "month"], "এক মাস": [1, "month"],
                     "গত বছর": [1, "year"], "এক বছর": [1, "year"]},
        "approximate": ["প্রায়", "কাছাকাছি", "মোটামুটি", "কয়েক", "about", "around"],
        "severity": {"হালকা": 3, "সামান্য": 2, "মাঝারি": 5, "তীব্র": 8, "খুব বেশি": 9,
                     "অসহ্য": 10},
        "symptoms": {
            "fever": ["জ্বর", "তাপমাত্রা", "গা গরম", "jor", "fever"],
            "pain": ["ব্যথা", "যন্ত্রণা", "ব্যাথা", "betha", "pain"],
            "headache": ["মাথাব্যথা", "মাথা ব্যথা", "মাইগ্রেন", "matha betha"],
            "respiratory": ["কাশি", "শ্বাসকষ্ট", "হাঁপানি", "kashi", "cough"],
            "digestive": ["পেট", "পেটব্যথা", "গ্যাস", "বদহজম", "অম্বল", "বমি", "গা গোলানো"],
            "bowel": ["পায়খানা", "মল", "পাতলা পায়খানা", "কোষ্ঠকাঠিন্য", "ডায়রিয়া"],
            "urinary": ["প্রস্রাব", "মূত্র", "prosrab", "urine"],
            "skin": ["ত্বক", "চামড়া", "চুলকানি", "র‍্যাশ", "ফোঁড়া"],
            "fatigue": ["দুর্বলতা", "ক্লান্তি", "দুর্বল", "শক্তি নেই"],
            "sleep": ["ঘুম", "ঘুম হয় না", "অনিদ্রা", "ghum"],
            "joint": ["গাঁট", "হাঁটু", "কোমর ব্যথা", "শরীর ব্যথা", "গিঁট"],
            "menstrual": ["মাসিক", "পিরিয়ড", "ঋতুস্রাব", "period"],
            "mental": ["মানসিক চাপ", "দুশ্চিন্তা", "উদ্বেগ", "মন খারাপ", "বিষণ্ণ"],
            "bleeding": ["রক্ত", "রক্তপাত", "রক্ত পড়া", "rokto", "blood"],
        },
        "options": {
            "burning": ["জ্বালা", "জ্বালাপোড়া", "jala"], "cramping": ["মোচড়", "খিঁচুনি"],
            "stabbing": ["খোঁচা", "ছুরির মতো"], "dull_ache": ["চিনচিনে", "মৃদু ব্যথা"],
            "throbbing": ["দপদপ", "দপদপ করা"], "pressing": ["চাপ", "ভারী"],
            "shooting": ["ঝিলিক", "ছড়িয়ে পড়া"],
            "upper_abdomen": ["পেটের উপরে", "নাভির উপরে"],
            "lower_abdomen": ["পেটের নিচে", "নাভির নিচে"],
            "chest": ["বুক", "buk"], "head": ["মাথা", "matha"], "back": ["পিঠ", "কোমর"],
            "neck": ["ঘাড়"], "limb": ["হাত", "পা", "কাঁধ"],
            "sudden": ["হঠাৎ", "একদম", "hothat"], "gradual": ["ধীরে ধীরে", "আস্তে আস্তে"],
            "improving": ["ভালো", "কমছে", "আরাম"], "worsening": ["খারাপ", "বাড়ছে"],
            "unchanged": ["একই", "পরিবর্তন নেই"], "fluctuating": ["কখনো কম কখনো বেশি"],
            "constant": ["সব সময়", "একটানা"], "intermittent": ["আসে যায়", "মাঝে মাঝে"],
            "worse_after_eating": ["খাওয়ার পরে"], "better_after_eating": ["খেলে আরাম"],
            "worse_when_empty": ["খালি পেটে"], "dry": ["শুকনো"], "productive": ["কফ"],
            "yes": ["হ্যাঁ"], "no": ["না"],
        },
        "sites": {},
    },
    "ta": {
        "affirm": ["ஆம்", "ஆமாம்", "சரி", "இருக்கு", "உள்ளது", "aam", "yes"],
        "deny": ["இல்லை", "இல்ல", "கிடையாது", "இல்லைன்னு", "illai", "no"],
        "unsure": ["ஒருவேளை", "தெரியல", "தெரியவில்லை", "சில நேரம்", "maybe"],
        "negation": {"cues": ["இல்லை", "இல்ல", "கிடையாது", "இன்றி", "illai", "no", "not"],
                     "boundaries": ["ஆனால்", "இருந்தாலும்", "but", "aanal"],
                     "sentence_final": True},
        "numbers": {"ஒன்று": 1, "ஒரு": 1, "இரண்டு": 2, "மூன்று": 3, "நான்கு": 4, "ஐந்து": 5,
                    "ஆறு": 6, "ஏழு": 7, "எட்டு": 8, "ஒன்பது": 9, "பத்து": 10, "அரை": 0.5,
                    "ஒன்று": 1, "onnu": 1, "rendu": 2},
        "duration_units": {"hour": ["மணி", "மணிநேரம்", "hour", "hours"],
                           "day": ["நாள்", "நாட்கள்", "நாளா", "day", "days"],
                           "week": ["வாரம்", "வாரங்கள்", "week", "weeks"],
                           "month": ["மாதம்", "மாதங்கள்", "month", "months"],
                           "year": ["வருடம்", "ஆண்டு", "year", "years"]},
        "temporal": {"இன்று": [0, "day"], "இன்னைக்கு": [0, "day"], "நேற்று": [1, "day"],
                     "நேற்றிலிருந்து": [1, "day"], "சில நாட்கள்": [3, "day"],
                     "கடந்த வாரம்": [1, "week"], "ஒரு வாரம்": [1, "week"],
                     "கடந்த மாதம்": [1, "month"], "ஒரு மாதம்": [1, "month"],
                     "கடந்த ஆண்டு": [1, "year"], "ஒரு வருடம்": [1, "year"]},
        "approximate": ["சுமார்", "ஏறக்குறைய", "கிட்டத்தட்ட", "சில", "about", "around"],
        "severity": {"லேசான": 3, "கொஞ்சம்": 2, "மிதமான": 5, "கடுமையான": 8, "மிக அதிகம்": 9,
                     "தாங்க முடியாத": 10},
        "symptoms": {
            "fever": ["காய்ச்சல்", "ஜுரம்", "வெப்பநிலை", "kaichal", "fever"],
            "pain": ["வலி", "வேதனை", "நோவு", "vali", "pain"],
            "headache": ["தலைவலி", "தலை வலி", "ஒற்றைத் தலைவலி", "thalaivali"],
            "respiratory": ["இருமல்", "மூச்சுத் திணறல்", "ஆஸ்துமா", "irumal", "cough"],
            "digestive": ["வயிறு", "வயிற்று வலி", "வாயு", "அஜீரணம்", "நெஞ்செரிச்சல்",
                          "வாந்தி", "குமட்டல்"],
            "bowel": ["மலம்", "பேதி", "மலச்சிக்கல்", "வயிற்றுப்போக்கு"],
            "urinary": ["சிறுநீர்", "மூத்திரம்", "urine"],
            "skin": ["தோல்", "சரும", "அரிப்பு", "தடிப்பு", "கொப்புளம்"],
            "fatigue": ["சோர்வு", "பலவீனம்", "தளர்ச்சி", "சக்தி இல்லை"],
            "sleep": ["தூக்கம்", "தூக்கமின்மை", "thookam"],
            "joint": ["மூட்டு", "முழங்கால்", "இடுப்பு வலி", "உடல் வலி"],
            "menstrual": ["மாதவிடாய்", "பீரியட்ஸ்", "மாதவிலக்கு"],
            "mental": ["மன அழுத்தம்", "கவலை", "பதற்றம்", "மனச்சோர்வு"],
            "bleeding": ["இரத்தம்", "ரத்தம்", "இரத்தப்போக்கு", "blood"],
        },
        "options": {
            "burning": ["எரிச்சல்", "எரியுது"], "cramping": ["பிடிப்பு", "வலிப்பு"],
            "stabbing": ["குத்துவது", "ஊசி போல"], "dull_ache": ["மந்தமான வலி"],
            "throbbing": ["படபடப்பு", "துடிப்பு"], "pressing": ["அழுத்தம்", "கனம்"],
            "shooting": ["பாய்வது"],
            "upper_abdomen": ["வயிற்றின் மேல்", "தொப்புளுக்கு மேல்"],
            "lower_abdomen": ["வயிற்றின் கீழ்", "தொப்புளுக்கு கீழ்"],
            "chest": ["மார்பு", "நெஞ்சு"], "head": ["தலை"], "back": ["முதுகு", "இடுப்பு"],
            "neck": ["கழுத்து"], "limb": ["கை", "கால்", "தோள்"],
            "sudden": ["திடீரென", "உடனே"], "gradual": ["மெதுவாக", "படிப்படியாக"],
            "improving": ["குறைகிறது", "நல்லது"], "worsening": ["அதிகமாகிறது", "மோசம்"],
            "unchanged": ["அப்படியே", "மாற்றம் இல்லை"], "fluctuating": ["ஏற்ற இறக்கம்"],
            "constant": ["எப்போதும்", "தொடர்ந்து"], "intermittent": ["வந்து போகிறது"],
            "worse_after_eating": ["சாப்பிட்ட பிறகு"], "better_after_eating": ["சாப்பிட்டால் நிவாரணம்"],
            "worse_when_empty": ["வெறும் வயிற்றில்"], "dry": ["வறட்டு"], "productive": ["சளி"],
            "yes": ["ஆம்"], "no": ["இல்லை"],
        },
        "sites": {},
    },
    "te": {
        "affirm": ["అవును", "ఔను", "సరే", "ఉంది", "avunu", "yes"],
        "deny": ["కాదు", "లేదు", "లేద", "ఎప్పుడూ లేదు", "ledu", "kadu", "no"],
        "unsure": ["బహుశా", "తెలియదు", "చెప్పలేను", "కొన్నిసార్లు", "maybe"],
        "negation": {"cues": ["కాదు", "లేదు", "లేద", "లేకుండా", "ledu", "kadu", "no", "not"],
                     "boundaries": ["కానీ", "అయితే", "but", "kani"],
                     "sentence_final": True},
        "numbers": {"ఒకటి": 1, "ఒక": 1, "రెండు": 2, "మూడు": 3, "నాలుగు": 4, "ఐదు": 5,
                    "ఆరు": 6, "ఏడు": 7, "ఎనిమిది": 8, "తొమ్మిది": 9, "పది": 10, "సగం": 0.5,
                    "okati": 1, "rendu": 2, "moodu": 3},
        "duration_units": {"hour": ["గంట", "గంటలు", "hour", "hours"],
                           "day": ["రోజు", "రోజులు", "day", "days"],
                           "week": ["వారం", "వారాలు", "week", "weeks"],
                           "month": ["నెల", "నెలలు", "month", "months"],
                           "year": ["సంవత్సరం", "ఏడాది", "year", "years"]},
        "temporal": {"ఈరోజు": [0, "day"], "నిన్న": [1, "day"], "నిన్నటి నుండి": [1, "day"],
                     "కొన్ని రోజులు": [3, "day"], "గత వారం": [1, "week"],
                     "ఒక వారం": [1, "week"], "గత నెల": [1, "month"], "ఒక నెల": [1, "month"],
                     "గత సంవత్సరం": [1, "year"], "ఒక సంవత్సరం": [1, "year"]},
        "approximate": ["సుమారు", "దాదాపు", "కొన్ని", "about", "around"],
        "severity": {"తేలికపాటి": 3, "కొంచెం": 2, "మధ్యస్థం": 5, "తీవ్రమైన": 8,
                     "చాలా ఎక్కువ": 9, "భరించలేని": 10},
        "symptoms": {
            "fever": ["జ్వరం", "వేడి", "ఉష్ణోగ్రత", "jwaram", "fever"],
            "pain": ["నొప్పి", "బాధ", "noppi", "pain"],
            "headache": ["తలనొప్పి", "తల నొప్పి", "పార్శ్వనొప్పి"],
            "respiratory": ["దగ్గు", "శ్వాస ఇబ్బంది", "ఆస్తమా", "daggu", "cough"],
            "digestive": ["కడుపు", "కడుపునొప్పి", "గ్యాస్", "అజీర్ణం", "గుండెల్లో మంట",
                          "వాంతి", "వికారం"],
            "bowel": ["మలం", "విరేచనాలు", "మలబద్ధకం", "నీళ్ళ విరేచనాలు"],
            "urinary": ["మూత్రం", "మూత్రవిసర్జన", "urine"],
            "skin": ["చర్మం", "దురద", "దద్దుర్లు", "కురుపులు"],
            "fatigue": ["బలహీనత", "అలసట", "నీరసం", "శక్తి లేదు"],
            "sleep": ["నిద్ర", "నిద్ర పట్టడం లేదు", "నిద్రలేమి"],
            "joint": ["కీళ్ళు", "మోకాలు", "నడుము నొప్పి", "ఒళ్ళు నొప్పులు"],
            "menstrual": ["రుతుస్రావం", "పీరియడ్స్", "నెలసరి"],
            "mental": ["ఒత్తిడి", "ఆందోళన", "కంగారు", "నిరాశ"],
            "bleeding": ["రక్తం", "రక్తస్రావం", "blood"],
        },
        "options": {
            "burning": ["మంట", "మండుతోంది"], "cramping": ["పట్టేయడం", "తిప్పడం"],
            "stabbing": ["గుచ్చినట్టు", "సూదిలా"], "dull_ache": ["మందమైన నొప్పి"],
            "throbbing": ["కొట్టుకోవడం"], "pressing": ["ఒత్తిడి", "బరువు"],
            "shooting": ["సాగడం"],
            "upper_abdomen": ["కడుపు పైన", "బొడ్డు పైన"],
            "lower_abdomen": ["కడుపు కింద", "బొడ్డు కింద"],
            "chest": ["ఛాతీ", "గుండె"], "head": ["తల"], "back": ["వీపు", "నడుము"],
            "neck": ["మెడ"], "limb": ["చెయ్యి", "కాలు", "భుజం"],
            "sudden": ["అకస్మాత్తుగా", "ఒక్కసారిగా"], "gradual": ["నెమ్మదిగా", "క్రమంగా"],
            "improving": ["తగ్గుతోంది", "మెరుగు"], "worsening": ["పెరుగుతోంది", "దిగజారుతోంది"],
            "unchanged": ["అలాగే", "మార్పు లేదు"], "fluctuating": ["హెచ్చుతగ్గులు"],
            "constant": ["ఎప్పుడూ", "నిరంతరం"], "intermittent": ["వస్తూ పోతూ"],
            "worse_after_eating": ["తిన్న తర్వాత"], "better_after_eating": ["తింటే ఉపశమనం"],
            "worse_when_empty": ["ఖాళీ కడుపుతో"], "dry": ["పొడి"], "productive": ["కఫం"],
            "yes": ["అవును"], "no": ["కాదు"],
        },
        "sites": {},
    },
    "mr": {
        "affirm": ["होय", "हो", "बरोबर", "आहे", "हा", "ho", "yes"],
        "deny": ["नाही", "ना", "कधीच नाही", "नाहीये", "nahi", "no"],
        "unsure": ["कदाचित", "माहीत नाही", "सांगू शकत नाही", "कधीकधी", "maybe"],
        "negation": {"cues": ["नाही", "ना", "नाहीये", "शिवाय", "nahi", "no", "not"],
                     "boundaries": ["पण", "परंतु", "मात्र", "but", "pan"],
                     "sentence_final": True},
        "numbers": {"एक": 1, "दोन": 2, "तीन": 3, "चार": 4, "पाच": 5, "सहा": 6, "सात": 7,
                    "आठ": 8, "नऊ": 9, "दहा": 10, "अर्धा": 0.5, "काही": 3,
                    "ek": 1, "don": 2, "teen": 3},
        "duration_units": {"hour": ["तास", "तासांपासून", "hour", "hours"],
                           "day": ["दिवस", "दिवसांपासून", "day", "days"],
                           "week": ["आठवडा", "आठवडे", "week", "weeks"],
                           "month": ["महिना", "महिने", "month", "months"],
                           "year": ["वर्ष", "वर्षे", "year", "years"]},
        "temporal": {"आज": [0, "day"], "काल": [1, "day"], "कालपासून": [1, "day"],
                     "परवा": [2, "day"], "काही दिवस": [3, "day"],
                     "गेल्या आठवड्यात": [1, "week"], "एक आठवडा": [1, "week"],
                     "गेल्या महिन्यात": [1, "month"], "एक महिना": [1, "month"],
                     "गेल्या वर्षी": [1, "year"], "एक वर्ष": [1, "year"]},
        "approximate": ["सुमारे", "जवळपास", "अंदाजे", "काही", "about", "around"],
        "severity": {"सौम्य": 3, "थोडा": 2, "मध्यम": 5, "तीव्र": 8, "खूप जास्त": 9,
                     "असह्य": 10},
        "symptoms": {
            "fever": ["ताप", "तापमान", "अंग गरम", "taap", "fever"],
            "pain": ["वेदना", "दुखणे", "दुखते", "त्रास", "pain"],
            "headache": ["डोकेदुखी", "डोके दुखणे", "मायग्रेन"],
            "respiratory": ["खोकला", "दम लागणे", "श्वास", "दमा", "khokla", "cough"],
            "digestive": ["पोट", "पोटदुखी", "गॅस", "अपचन", "जळजळ", "उलटी", "मळमळ"],
            "bowel": ["शौच", "जुलाब", "बद्धकोष्ठता", "संडास", "पातळ शौच"],
            "urinary": ["लघवी", "मूत्र", "laghvi", "urine"],
            "skin": ["त्वचा", "कातडी", "खाज", "पुरळ", "गळू"],
            "fatigue": ["अशक्तपणा", "थकवा", "दमछाक", "शक्ती नाही"],
            "sleep": ["झोप", "झोप लागत नाही", "निद्रानाश"],
            "joint": ["सांधे", "गुडघा", "कंबरदुखी", "अंगदुखी"],
            "menstrual": ["मासिक पाळी", "पाळी", "पिरियड"],
            "mental": ["ताण", "चिंता", "काळजी", "उदासी", "नैराश्य"],
            "bleeding": ["रक्त", "रक्तस्राव", "रक्त येणे", "blood"],
        },
        "options": {
            "burning": ["जळजळ", "आग होणे"], "cramping": ["पिळवटणे", "आकडी"],
            "stabbing": ["टोचल्यासारखे", "सुईसारखे"], "dull_ache": ["मंद दुखणे"],
            "throbbing": ["ठणकणे"], "pressing": ["दाब", "जडपणा"], "shooting": ["सणक"],
            "upper_abdomen": ["पोटाच्या वर", "बेंबीच्या वर"],
            "lower_abdomen": ["पोटाच्या खाली", "बेंबीच्या खाली"],
            "chest": ["छाती"], "head": ["डोके"], "back": ["पाठ", "कंबर"],
            "neck": ["मान"], "limb": ["हात", "पाय", "खांदा"],
            "sudden": ["अचानक", "एकदम"], "gradual": ["हळूहळू", "टप्प्याटप्प्याने"],
            "improving": ["कमी होत आहे", "बरे"], "worsening": ["वाढत आहे", "खराब"],
            "unchanged": ["तसेच", "बदल नाही"], "fluctuating": ["कमी जास्त"],
            "constant": ["सतत", "नेहमी"], "intermittent": ["येते जाते", "कधीकधी"],
            "worse_after_eating": ["जेवणानंतर"], "better_after_eating": ["जेवल्यावर आराम"],
            "worse_when_empty": ["उपाशीपोटी"], "dry": ["कोरडा"], "productive": ["कफ"],
            "yes": ["होय"], "no": ["नाही"],
        },
        "sites": {},
    },
    "gu": {
        "affirm": ["હા", "હાં", "જી", "બરાબર", "છે", "ha", "yes"],
        "deny": ["ના", "નથી", "કદી નહીં", "નહીં", "na", "nathi", "no"],
        "unsure": ["કદાચ", "ખબર નથી", "કહી શકતો નથી", "ક્યારેક", "maybe"],
        "negation": {"cues": ["ના", "નથી", "નહીં", "વગર", "na", "nathi", "no", "not"],
                     "boundaries": ["પણ", "પરંતુ", "છતાં", "but", "pan"],
                     "sentence_final": True},
        "numbers": {"એક": 1, "બે": 2, "ત્રણ": 3, "ચાર": 4, "પાંચ": 5, "છ": 6, "સાત": 7,
                    "આઠ": 8, "નવ": 9, "દસ": 10, "અડધું": 0.5, "થોડા": 3,
                    "ek": 1, "be": 2, "tran": 3},
        "duration_units": {"hour": ["કલાક", "કલાકથી", "hour", "hours"],
                           "day": ["દિવસ", "દિવસથી", "day", "days"],
                           "week": ["અઠવાડિયું", "અઠવાડિયા", "week", "weeks"],
                           "month": ["મહિનો", "મહિના", "month", "months"],
                           "year": ["વર્ષ", "વરસ", "year", "years"]},
        "temporal": {"આજે": [0, "day"], "ગઈકાલે": [1, "day"], "ગઈકાલથી": [1, "day"],
                     "થોડા દિવસ": [3, "day"], "ગયા અઠવાડિયે": [1, "week"],
                     "એક અઠવાડિયું": [1, "week"], "ગયા મહિને": [1, "month"],
                     "એક મહિનો": [1, "month"], "ગયા વર્ષે": [1, "year"], "એક વર્ષ": [1, "year"]},
        "approximate": ["આશરે", "લગભગ", "અંદાજે", "થોડા", "about", "around"],
        "severity": {"હળવો": 3, "થોડો": 2, "મધ્યમ": 5, "તીવ્ર": 8, "ખૂબ વધારે": 9,
                     "અસહ્ય": 10},
        "symptoms": {
            "fever": ["તાવ", "તાપમાન", "શરીર ગરમ", "taav", "fever"],
            "pain": ["દુખાવો", "પીડા", "દુખે", "pain"],
            "headache": ["માથાનો દુખાવો", "માથું દુખે", "માઇગ્રેન"],
            "respiratory": ["ઉધરસ", "શ્વાસ", "દમ", "cough"],
            "digestive": ["પેટ", "પેટમાં દુખાવો", "ગેસ", "અપચો", "બળતરા", "ઊલટી", "ઊબકા"],
            "bowel": ["સંડાસ", "ઝાડા", "કબજિયાત", "પાતળા ઝાડા"],
            "urinary": ["પેશાબ", "મૂત્ર", "urine"],
            "skin": ["ચામડી", "ત્વચા", "ખંજવાળ", "ફોલ્લી", "ગુમડું"],
            "fatigue": ["નબળાઈ", "થાક", "શક્તિ નથી"],
            "sleep": ["ઊંઘ", "ઊંઘ આવતી નથી", "અનિદ્રા"],
            "joint": ["સાંધા", "ઘૂંટણ", "કમરનો દુખાવો", "શરીરનો દુખાવો"],
            "menstrual": ["માસિક", "પિરિયડ", "ઋતુસ્રાવ"],
            "mental": ["તણાવ", "ચિંતા", "ગભરાટ", "ઉદાસી"],
            "bleeding": ["લોહી", "રક્તસ્રાવ", "લોહી નીકળવું", "blood"],
        },
        "options": {
            "burning": ["બળતરા", "બળે છે"], "cramping": ["આંકડી", "ચૂંક"],
            "stabbing": ["ભોંકાય", "સોય જેવું"], "dull_ache": ["હળવો દુખાવો"],
            "throbbing": ["ધબકારા", "ટીસ"], "pressing": ["દબાણ", "ભાર"], "shooting": ["ઝટકો"],
            "upper_abdomen": ["પેટની ઉપર", "નાભિની ઉપર"],
            "lower_abdomen": ["પેટની નીચે", "નાભિની નીચે"],
            "chest": ["છાતી"], "head": ["માથું"], "back": ["પીઠ", "કમર"],
            "neck": ["ગરદન"], "limb": ["હાથ", "પગ", "ખભો"],
            "sudden": ["અચાનક", "એકદમ"], "gradual": ["ધીમે ધીમે", "ક્રમશઃ"],
            "improving": ["ઓછું થાય છે", "સારું"], "worsening": ["વધે છે", "ખરાબ"],
            "unchanged": ["એવું જ", "ફેરફાર નથી"], "fluctuating": ["ઓછું વત્તું"],
            "constant": ["સતત", "હંમેશા"], "intermittent": ["આવે જાય", "ક્યારેક"],
            "worse_after_eating": ["જમ્યા પછી"], "better_after_eating": ["જમવાથી રાહત"],
            "worse_when_empty": ["ખાલી પેટે"], "dry": ["સૂકી"], "productive": ["કફ"],
            "yes": ["હા"], "no": ["ના"],
        },
        "sites": {},
    },
    "kn": {
        "affirm": ["ಹೌದು", "ಸರಿ", "ಇದೆ", "ಹೂಂ", "houdu", "yes"],
        "deny": ["ಇಲ್ಲ", "ಅಲ್ಲ", "ಎಂದಿಗೂ ಇಲ್ಲ", "illa", "no"],
        "unsure": ["ಬಹುಶಃ", "ಗೊತ್ತಿಲ್ಲ", "ಹೇಳಲಾಗದು", "ಕೆಲವೊಮ್ಮೆ", "maybe"],
        "negation": {"cues": ["ಇಲ್ಲ", "ಅಲ್ಲ", "ಇಲ್ಲದೆ", "illa", "no", "not"],
                     "boundaries": ["ಆದರೆ", "ಆದಾಗ್ಯೂ", "but", "adare"],
                     "sentence_final": True},
        "numbers": {"ಒಂದು": 1, "ಎರಡು": 2, "ಮೂರು": 3, "ನಾಲ್ಕು": 4, "ಐದು": 5, "ಆರು": 6,
                    "ಏಳು": 7, "ಎಂಟು": 8, "ಒಂಬತ್ತು": 9, "ಹತ್ತು": 10, "ಅರ್ಧ": 0.5,
                    "ondu": 1, "eradu": 2, "mooru": 3},
        "duration_units": {"hour": ["ಗಂಟೆ", "ಗಂಟೆಗಳ", "hour", "hours"],
                           "day": ["ದಿನ", "ದಿನಗಳ", "day", "days"],
                           "week": ["ವಾರ", "ವಾರಗಳ", "week", "weeks"],
                           "month": ["ತಿಂಗಳು", "ತಿಂಗಳ", "month", "months"],
                           "year": ["ವರ್ಷ", "ವರ್ಷಗಳ", "year", "years"]},
        "temporal": {"ಇಂದು": [0, "day"], "ನಿನ್ನೆ": [1, "day"], "ನಿನ್ನೆಯಿಂದ": [1, "day"],
                     "ಕೆಲವು ದಿನ": [3, "day"], "ಕಳೆದ ವಾರ": [1, "week"],
                     "ಒಂದು ವಾರ": [1, "week"], "ಕಳೆದ ತಿಂಗಳು": [1, "month"],
                     "ಒಂದು ತಿಂಗಳು": [1, "month"], "ಕಳೆದ ವರ್ಷ": [1, "year"],
                     "ಒಂದು ವರ್ಷ": [1, "year"]},
        "approximate": ["ಸುಮಾರು", "ಹೆಚ್ಚುಕಡಿಮೆ", "ಅಂದಾಜು", "ಕೆಲವು", "about", "around"],
        "severity": {"ಸೌಮ್ಯ": 3, "ಸ್ವಲ್ಪ": 2, "ಮಧ್ಯಮ": 5, "ತೀವ್ರ": 8, "ತುಂಬಾ ಹೆಚ್ಚು": 9,
                     "ಸಹಿಸಲಾಗದ": 10},
        "symptoms": {
            "fever": ["ಜ್ವರ", "ಉಷ್ಣತೆ", "ಮೈ ಬಿಸಿ", "jwara", "fever"],
            "pain": ["ನೋವು", "ಬೇನೆ", "novu", "pain"],
            "headache": ["ತಲೆನೋವು", "ತಲೆ ನೋವು", "ಮೈಗ್ರೇನ್"],
            "respiratory": ["ಕೆಮ್ಮು", "ಉಸಿರಾಟದ ತೊಂದರೆ", "ಅಸ್ತಮಾ", "kemmu", "cough"],
            "digestive": ["ಹೊಟ್ಟೆ", "ಹೊಟ್ಟೆನೋವು", "ಗ್ಯಾಸ್", "ಅಜೀರ್ಣ", "ಎದೆ ಉರಿ",
                          "ವಾಂತಿ", "ವಾಕರಿಕೆ"],
            "bowel": ["ಮಲ", "ಭೇದಿ", "ಮಲಬದ್ಧತೆ", "ನೀರು ಭೇದಿ"],
            "urinary": ["ಮೂತ್ರ", "ಮೂತ್ರ ವಿಸರ್ಜನೆ", "urine"],
            "skin": ["ಚರ್ಮ", "ತುರಿಕೆ", "ದದ್ದು", "ಗುಳ್ಳೆ"],
            "fatigue": ["ದೌರ್ಬಲ್ಯ", "ಆಯಾಸ", "ಸುಸ್ತು", "ಶಕ್ತಿ ಇಲ್ಲ"],
            "sleep": ["ನಿದ್ರೆ", "ನಿದ್ರೆ ಬರುತ್ತಿಲ್ಲ", "ನಿದ್ರಾಹೀನತೆ"],
            "joint": ["ಕೀಲು", "ಮಂಡಿ", "ಸೊಂಟ ನೋವು", "ಮೈ ಕೈ ನೋವು"],
            "menstrual": ["ಋತುಸ್ರಾವ", "ಮುಟ್ಟು", "ಪೀರಿಯಡ್ಸ್"],
            "mental": ["ಒತ್ತಡ", "ಆತಂಕ", "ಚಿಂತೆ", "ಖಿನ್ನತೆ"],
            "bleeding": ["ರಕ್ತ", "ರಕ್ತಸ್ರಾವ", "blood"],
        },
        "options": {
            "burning": ["ಉರಿ", "ಉರಿಯುತ್ತದೆ"], "cramping": ["ಸೆಳೆತ", "ಹಿಡಿತ"],
            "stabbing": ["ಚುಚ್ಚುವುದು", "ಸೂಜಿಯಂತೆ"], "dull_ache": ["ಮಂದ ನೋವು"],
            "throbbing": ["ಬಡಿತ"], "pressing": ["ಒತ್ತಡ", "ಭಾರ"], "shooting": ["ಸಿಡಿತ"],
            "upper_abdomen": ["ಹೊಟ್ಟೆಯ ಮೇಲೆ", "ಹೊಕ್ಕುಳ ಮೇಲೆ"],
            "lower_abdomen": ["ಹೊಟ್ಟೆಯ ಕೆಳಗೆ", "ಹೊಕ್ಕುಳ ಕೆಳಗೆ"],
            "chest": ["ಎದೆ"], "head": ["ತಲೆ"], "back": ["ಬೆನ್ನು", "ಸೊಂಟ"],
            "neck": ["ಕುತ್ತಿಗೆ"], "limb": ["ಕೈ", "ಕಾಲು", "ಭುಜ"],
            "sudden": ["ಇದ್ದಕ್ಕಿದ್ದಂತೆ", "ಒಮ್ಮೆಲೇ"], "gradual": ["ನಿಧಾನವಾಗಿ", "ಕ್ರಮೇಣ"],
            "improving": ["ಕಡಿಮೆಯಾಗುತ್ತಿದೆ", "ಚೆನ್ನಾಗಿದೆ"], "worsening": ["ಹೆಚ್ಚಾಗುತ್ತಿದೆ"],
            "unchanged": ["ಹಾಗೆಯೇ", "ಬದಲಾವಣೆ ಇಲ್ಲ"], "fluctuating": ["ಏರಿಳಿತ"],
            "constant": ["ಯಾವಾಗಲೂ", "ನಿರಂತರ"], "intermittent": ["ಬಂದು ಹೋಗುತ್ತದೆ"],
            "worse_after_eating": ["ತಿಂದ ನಂತರ"], "better_after_eating": ["ತಿಂದರೆ ಆರಾಮ"],
            "worse_when_empty": ["ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ"], "dry": ["ಒಣ"], "productive": ["ಕಫ"],
            "yes": ["ಹೌದು"], "no": ["ಇಲ್ಲ"],
        },
        "sites": {},
    },
    "pa": {
        "affirm": ["ਹਾਂ", "ਜੀ", "ਠੀਕ", "ਸਹੀ", "ਹੈ", "haan", "yes"],
        "deny": ["ਨਹੀਂ", "ਨਾ", "ਕਦੇ ਨਹੀਂ", "ਨਈਂ", "nahi", "no"],
        "unsure": ["ਸ਼ਾਇਦ", "ਪਤਾ ਨਹੀਂ", "ਕਹਿ ਨਹੀਂ ਸਕਦੇ", "ਕਦੇ-ਕਦੇ", "maybe"],
        "negation": {"cues": ["ਨਹੀਂ", "ਨਾ", "ਨਈਂ", "ਬਿਨਾਂ", "nahi", "no", "not"],
                     "boundaries": ["ਪਰ", "ਲੇਕਿਨ", "ਹਾਲਾਂਕਿ", "but", "par"],
                     "sentence_final": True},
        "numbers": {"ਇੱਕ": 1, "ਦੋ": 2, "ਤਿੰਨ": 3, "ਚਾਰ": 4, "ਪੰਜ": 5, "ਛੇ": 6, "ਸੱਤ": 7,
                    "ਅੱਠ": 8, "ਨੌਂ": 9, "ਦਸ": 10, "ਅੱਧਾ": 0.5, "ਕੁਝ": 3,
                    "ik": 1, "do": 2, "tin": 3},
        "duration_units": {"hour": ["ਘੰਟਾ", "ਘੰਟੇ", "hour", "hours"],
                           "day": ["ਦਿਨ", "ਦਿਨਾਂ", "day", "days"],
                           "week": ["ਹਫ਼ਤਾ", "ਹਫ਼ਤੇ", "ਹਫਤਾ", "week", "weeks"],
                           "month": ["ਮਹੀਨਾ", "ਮਹੀਨੇ", "month", "months"],
                           "year": ["ਸਾਲ", "ਵਰ੍ਹਾ", "year", "years"]},
        "temporal": {"ਅੱਜ": [0, "day"], "ਕੱਲ੍ਹ": [1, "day"], "ਕੱਲ੍ਹ ਤੋਂ": [1, "day"],
                     "ਕੁਝ ਦਿਨ": [3, "day"], "ਪਿਛਲੇ ਹਫ਼ਤੇ": [1, "week"],
                     "ਇੱਕ ਹਫ਼ਤਾ": [1, "week"], "ਪਿਛਲੇ ਮਹੀਨੇ": [1, "month"],
                     "ਇੱਕ ਮਹੀਨਾ": [1, "month"], "ਪਿਛਲੇ ਸਾਲ": [1, "year"],
                     "ਇੱਕ ਸਾਲ": [1, "year"]},
        "approximate": ["ਲਗਭਗ", "ਕਰੀਬ", "ਤਕਰੀਬਨ", "ਕੁਝ", "about", "around"],
        "severity": {"ਹਲਕਾ": 3, "ਥੋੜ੍ਹਾ": 2, "ਦਰਮਿਆਨਾ": 5, "ਤੇਜ਼": 8, "ਬਹੁਤ ਜ਼ਿਆਦਾ": 9,
                     "ਅਸਹਿ": 10},
        "symptoms": {
            "fever": ["ਬੁਖ਼ਾਰ", "ਬੁਖਾਰ", "ਤਾਪਮਾਨ", "ਸਰੀਰ ਗਰਮ", "bukhar", "fever"],
            "pain": ["ਦਰਦ", "ਪੀੜ", "ਦੁਖਦਾ", "dard", "pain"],
            "headache": ["ਸਿਰ ਦਰਦ", "ਸਿਰਦਰਦ", "ਮਾਈਗਰੇਨ"],
            "respiratory": ["ਖੰਘ", "ਸਾਹ", "ਸਾਹ ਚੜ੍ਹਨਾ", "ਦਮਾ", "khang", "cough"],
            "digestive": ["ਪੇਟ", "ਪੇਟ ਦਰਦ", "ਗੈਸ", "ਬਦਹਜ਼ਮੀ", "ਸੜਨ", "ਉਲਟੀ", "ਜੀਅ ਕੱਚਾ"],
            "bowel": ["ਟੱਟੀ", "ਦਸਤ", "ਕਬਜ਼", "ਪਤਲੀ ਟੱਟੀ"],
            "urinary": ["ਪਿਸ਼ਾਬ", "ਮੂਤਰ", "urine"],
            "skin": ["ਚਮੜੀ", "ਖਾਰਸ਼", "ਧੱਫੜ", "ਫੋੜੇ"],
            "fatigue": ["ਕਮਜ਼ੋਰੀ", "ਥਕਾਵਟ", "ਤਾਕਤ ਨਹੀਂ"],
            "sleep": ["ਨੀਂਦ", "ਨੀਂਦ ਨਹੀਂ ਆਉਂਦੀ", "ਅਨੀਂਦਰਾ"],
            "joint": ["ਜੋੜ", "ਗੋਡਾ", "ਲੱਕ ਦਰਦ", "ਸਰੀਰ ਦਰਦ"],
            "menstrual": ["ਮਾਹਵਾਰੀ", "ਪੀਰੀਅਡ", "ਮਾਸਿਕ"],
            "mental": ["ਤਣਾਅ", "ਚਿੰਤਾ", "ਘਬਰਾਹਟ", "ਉਦਾਸੀ"],
            "bleeding": ["ਖ਼ੂਨ", "ਖੂਨ", "ਖ਼ੂਨ ਵਗਣਾ", "blood"],
        },
        "options": {
            "burning": ["ਸੜਨ", "ਜਲਨ"], "cramping": ["ਮਰੋੜ", "ਖਿਚਾਅ"],
            "stabbing": ["ਚੁਭਣ", "ਸੂਈ ਵਾਂਗ"], "dull_ache": ["ਹਲਕਾ ਦਰਦ"],
            "throbbing": ["ਟੀਸ", "ਧੜਕਣ"], "pressing": ["ਦਬਾਅ", "ਭਾਰ"], "shooting": ["ਝਟਕਾ"],
            "upper_abdomen": ["ਪੇਟ ਦੇ ਉੱਪਰ", "ਧੁੰਨੀ ਤੋਂ ਉੱਪਰ"],
            "lower_abdomen": ["ਪੇਟ ਦੇ ਹੇਠਾਂ", "ਧੁੰਨੀ ਤੋਂ ਹੇਠਾਂ"],
            "chest": ["ਛਾਤੀ"], "head": ["ਸਿਰ"], "back": ["ਪਿੱਠ", "ਲੱਕ"],
            "neck": ["ਗਰਦਨ"], "limb": ["ਬਾਂਹ", "ਲੱਤ", "ਮੋਢਾ"],
            "sudden": ["ਅਚਾਨਕ", "ਇਕਦਮ"], "gradual": ["ਹੌਲੀ-ਹੌਲੀ", "ਹੌਲੀ ਹੌਲੀ"],
            "improving": ["ਘੱਟ ਰਿਹਾ", "ਠੀਕ"], "worsening": ["ਵਧ ਰਿਹਾ", "ਖ਼ਰਾਬ"],
            "unchanged": ["ਉਹੀ", "ਕੋਈ ਬਦਲਾਅ ਨਹੀਂ"], "fluctuating": ["ਘੱਟ ਵੱਧ"],
            "constant": ["ਹਰ ਵੇਲੇ", "ਲਗਾਤਾਰ"], "intermittent": ["ਆਉਂਦਾ ਜਾਂਦਾ"],
            "worse_after_eating": ["ਖਾਣ ਤੋਂ ਬਾਅਦ"], "better_after_eating": ["ਖਾਣ ਨਾਲ ਆਰਾਮ"],
            "worse_when_empty": ["ਖਾਲੀ ਪੇਟ"], "dry": ["ਸੁੱਕੀ"], "productive": ["ਬਲਗ਼ਮ"],
            "yes": ["ਹਾਂ"], "no": ["ਨਹੀਂ"],
        },
        "sites": {},
    },
}

VOCABULARY.update(_MORE)

# Every language also accepts the Latin-script words a patient types on a phone
# keyboard that has no Devanagari on it. Merged rather than listed nine times.
for _language, _entry in VOCABULARY.items():
    if _language == "en":
        continue
    for _domain, _words in _LATIN_FALLBACK.items():
        _entry["symptoms"].setdefault(_domain, [])
        _entry["symptoms"][_domain] = list(
            dict.fromkeys([*_entry["symptoms"][_domain], *_words])
        )

__all__ = ["VOCABULARY"]
