/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Answers as long as the process is running.
         *
         *     Deliberately touches nothing: a liveness probe that queries the database
         *     restarts a healthy container every time the database hiccups.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness. Content loaded, providers built, database reachable.
         *
         *     Also reports which providers are live, so "what is this deployment
         *     actually running" is one curl rather than a guess.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The question content the kiosk and the patient app walk
         * @description The current bundle, or `304` when the client already has it.
         *
         *     The `ETag` is a hash of the body rather than the version string, so an edit
         *     to a prompt that nobody remembered to bump `content_version` for still
         *     invalidates every cached copy. The version is what a human reads in a
         *     changelog; the ETag is what is actually enforced.
         *
         *     80 KB of Devanagari and English prompts on what may be a patient's mobile
         *     data, fetched on every app launch. The 304 is not an optimisation detail —
         *     it is the difference between an app that opens instantly on a bad connection
         *     and one that does not.
         */
        get: operations["bundle_api_v1_content_bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/bundle/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current content version, without downloading the bundle
         * @description A cheap check for a client deciding whether to refresh on a metered
         *     connection.
         */
        get: operations["bundle_version_api_v1_content_bundle_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The consent notice a patient is shown before intake
         * @description The purposes, in every language they are authored in — §11, DPDP.
         *
         *     Unauthenticated for the same reason the bundle is: a patient must be able to
         *     read what they are agreeing to before they have agreed to anything, and
         *     certainly before they have signed in.
         *
         *     `source` filters purposes by where they apply. `raw_audio_retention` is
         *     annotated `applies_to: [kiosk]` in the content, because the patient app has
         *     no microphone — asking for consent to retain audio it cannot capture would
         *     produce an artefact describing something that never happened, and the DPDP
         *     obligation is to be able to show exactly what the patient agreed to.
         */
        get: operations["consent_notice_api_v1_content_consent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hospitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hospitals a patient can submit an intake to
         * @description Active hospitals only.
         *
         *     A deactivated hospital stays in the database — its intakes and reports must
         *     remain readable — but it is not offered to a patient about to travel there.
         */
        get: operations["hospitals_api_v1_hospitals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a one-time code to a phone number
         * @description Issue a code.
         *
         *     Always answers the same way for a well-formed number, whether or not that
         *     number has ever been seen. Telling a caller "no account for this number"
         *     would turn the endpoint into a membership oracle for patients of an AYUSH
         *     hospital.
         */
        post: operations["request_code_api_v1_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a code for a patient session token
         * @description Check the code and issue a session.
         *
         *     The token goes into the phone's Keychain or Keystore, never into shared
         *     preferences — 2/3 §7.1. The server stores only its hash.
         */
        post: operations["verify_api_v1_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke this patient session
         * @description Revoke the presented token.
         *
         *     Deliberately not role-guarded and deliberately always `204`. A sign-out that
         *     refuses an already-invalid token tells the caller whether it was valid, and
         *     an app clearing its own state on logout should not have to care either way —
         *     2/3 §10 requires it to wipe local storage regardless of what the server says.
         */
        post: operations["sign_out_api_v1_auth_otp_sign_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a completed intake from a kiosk
         * @description Take one kiosk payload all the way to a persisted record.
         *
         *     Idempotent on `Idempotency-Key`: the same key replayed returns the original
         *     result and creates nothing. The Jetson retries, and a hospital LAN gives it
         *     reason to.
         *
         *     A payload that fails its contract goes to the repair path, not to a
         *     rejection — see §5.1. One that cannot be repaired is stored raw and comes
         *     back with `needs_manual_review: true` and a 200, because a device that keeps
         *     retrying an unparseable payload eventually drops it, and the answers are
         *     worth more than the status code.
         */
        post: operations["ingest_api_v1_intakes_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The canonical record for one intake
         * @description Everything on the record, with contradictions recomputed.
         */
        get: operations["get_intake_api_v1_intakes__intake_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The physician report
         * @description Build and return the report.
         *
         *     Regenerated on every call rather than served from cache: a document that
         *     arrived after the last read changes the document section, and a physician
         *     reading a stale report is worse than one waiting a few hundred milliseconds.
         */
        get: operations["get_report_api_v1_intakes__intake_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/facts/{fact_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What one fact rests on
         * @description The transcript turn or document region behind a line of the report.
         *
         *     This endpoint is why every fact carries a `SourceRef`. Without it the report
         *     is an assertion; with it, it is evidence a clinician can check in one click.
         */
        get: operations["get_evidence_api_v1_intakes__intake_id__facts__fact_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Physician confirms or amends the record
         * @description Sign off the record, or the fields named.
         *
         *     Writes new fact revisions recording who verified what and when; it does not
         *     edit the originals. Unsettled fields are skipped — an unresolved field with
         *     a physician's name on it would be a certainty increase with a signature.
         */
        post: operations["verify_api_v1_intakes__intake_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documents attached to an intake
         * @description Each with a short-lived signed URL.
         */
        get: operations["list_documents_api_v1_intakes__intake_id__documents_get"];
        put?: never;
        /**
         * Upload a document image for OCR
         * @description Store the image and queue it for reading.
         *
         *     **202, always.** Processing is asynchronous and nothing about the patient's
         *     experience waits on a model — they have already answered the questions, and
         *     the doctor sees the document section fill in when it fills in.
         *
         *     Where the work goes is `DOCUMENT_QUEUE`: a background task in this process
         *     locally, so `docker compose up` is a complete pipeline with no broker; a
         *     Pub/Sub message to a separate Cloud Run worker in the cloud. Both end at the
         *     same `DocumentService.process`.
         *
         *     The dispatch is awaited and its failure is *not* swallowed. Storing a
         *     photograph and then failing to queue it would leave a document that the
         *     physician is never shown and never told about; the kiosk is better off
         *     seeing the upload fail and sending it again.
         */
        post: operations["upload_document_api_v1_intakes__intake_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intakes/{intake_id}/documents/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an OCR result produced on the device
         * @description Take an extraction the Jetson produced on-device.
         *
         *     PP-OCRv5 Devanagari is 7.5 MB and Surya fits in 1.47 GB, so on-device OCR is
         *     viable — and a hospital may prefer that a photographed prescription never
         *     leaves the building. The image stays there; only the structured result
         *     crosses the network, and everything downstream is identical to the cloud
         *     path.
         *
         *     The redaction pass runs on this input too. An extraction is not trusted
         *     because it came from our own device.
         */
        post: operations["accept_results_api_v1_intakes__intake_id__documents_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/content/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a stored document image (local storage backend only)
         * @description Serve an image from the local store.
         *
         *     Exists only so the laptop demo has working evidence links. The key is
         *     prefixed with the hospital id, and this check is what makes the prefix
         *     load-bearing rather than decorative: a caller cannot read another hospital's
         *     object by knowing its key.
         *
         *     In the deployed profile GCS signs the URL and this route is never called.
         */
        get: operations["document_content_api_v1_documents_content__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a patient reference
         * @description Identify a patient — or fail to, without blocking the intake.
         *
         *     ABHA is never mandatory. A failed or unavailable lookup comes back
         *     `verified: false` and the intake proceeds as a guest; the alternative is
         *     turning a patient away because a government API was down.
         *
         *     The `source` field is passed through verbatim. When it says `"mock"`, the
         *     answer came from the mock provider and the dashboard is expected to say so
         *     on screen.
         */
        post: operations["resolve_api_v1_patients_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/abha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link an ABHA address to the signed-in patient
         * @description Verify an ABHA address the patient offered — 2/3 §7.2.
         *
         *     **Never mandatory, and never a gate.** A failed or unavailable lookup comes
         *     back `verified: false` and the intake proceeds exactly as it would have; the
         *     entire app works with a phone number alone (§7.3). The alternative is
         *     turning a patient away because a government API was down, which is not a
         *     trade this project makes anywhere.
         *
         *     What linking buys is retrieval: a patient known here under an ABHA address
         *     has history to carry forward on screen 5.
         *
         *     `source` is passed through verbatim. When it says `"mock"` — which it does
         *     today — the app is expected to say so on screen, so nobody demos a mocked
         *     government integration as a live one.
         */
        post: operations["link_abha_api_v1_patients_me_abha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in patient's own prior intakes at this hospital
         * @description What screen 5 renders — 2/3 §5.
         *
         *     **Registered before `/{ref}/history`, and that ordering is load-bearing.**
         *     FastAPI matches in registration order, so were this second, a request for
         *     `/patients/me/history` would bind `ref="me"` on the staff-only route and be
         *     answered — or refused — as if `me` were a patient identifier.
         *
         *     **The patient comes from the session, never from the request.** There is no
         *     path parameter here to tamper with: `principal.patient_ref` is the peppered
         *     HMAC the token was issued against, so "my history" can only ever mean the
         *     holder of this token. That is the whole reason this is a separate route
         *     rather than the existing one with a different guard.
         *
         *     The returning-patient screen shows these back as "our record shows X — still
         *     correct?" per item. That is confirmation of what the hospital already holds,
         *     which the patient told them; it is not OCR output and it is not an
         *     interpretation, so it does not run into `2/3 §8`'s rule against showing
         *     extracted values to a patient.
         */
        get: operations["my_history_api_v1_patients_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{ref}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prior intakes for this patient at this hospital
         * @description Previous intakes, plus what the Jetson should pre-load.
         *
         *     `carry_forward` holds only **physician-verified** conditions, medicines and
         *     allergies. That restriction is the point: it lets the next intake ask "our
         *     record shows diabetes — still correct?" instead of starting fresh, without
         *     letting an unverified mishearing become permanent history by being repeated
         *     back to the patient as established fact.
         *
         *     **This hospital only.** Cross-hospital retrieval requires an ABDM consent
         *     artefact and is not implemented; `scope_note` says so in the response so a
         *     dashboard cannot imply otherwise.
         */
        get: operations["history_api_v1_patients__ref__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Intakes waiting for a doctor, in arrival order
         * @description The ordered list for a department.
         *
         *     Arrival order. A fired red-flag criterion pulls the row into
         *     `pending_alerts` so it cannot be scrolled past, but it does **not** move the
         *     intake up the list — reordering a waiting room on a machine's reading of a
         *     symptom is a triage decision, and this system does not make those.
         */
        get: operations["worklist_api_v1_worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{intake_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge a red-flag event
         * @description Record that a person has seen an alert.
         *
         *     Acknowledgement is a record of a human having looked, and nothing else. It
         *     escalates nothing, reorders nothing and notifies nobody automatically — what
         *     happens next is the acknowledging clinician's decision, made outside this
         *     system.
         *
         *     A second acknowledgement is a 409 rather than a silent success: two people
         *     each assuming the other has seen it is the failure worth being noisy about.
         */
        post: operations["acknowledge_api_v1_alerts__intake_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest quality counters
         * @description How often the repair path ran.
         *
         *     `repair_rate` counts intakes whose payload failed its contract and had to be
         *     restructured by a model. It should fall as the Jetson's extractor improves,
         *     and a number that moves in the right direction over a fortnight is a better
         *     argument than any slide.
         */
        get: operations["metrics_api_v1_metrics_ingest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a consent artefact
         * @description Store what the patient actually agreed to.
         *
         *     Immutable. A withdrawal or a re-take writes a new artefact that supersedes
         *     this one; nothing edits a row here, because a row that can be edited proves
         *     nothing about what was shown at the time.
         */
        post: operations["record_consent_api_v1_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/{consent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a consent artefact */
        get: operations["get_consent_api_v1_consent__consent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fhir/intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * FHIR R4 bundle for one intake
         * @description Patient, Encounter, Condition, Observation, MedicationStatement,
         *     DocumentReference.
         *
         *     Codes appear only where a mapping exists. A field with no code gets `text`
         *     and no `coding` — a valid `CodeableConcept`, and the honest representation
         *     of "we know what this is, we have no code for it". A guessed code in an
         *     exchangeable document is a wrong diagnosis in someone's permanent record.
         */
        get: operations["intake_bundle_api_v1_fhir_intakes__intake_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_terminology_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/CodeSystem/{system}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code System
         * @description FHIR R4 `CodeSystem` for one terminology.
         */
        get: operations["code_system_api_v1_terminology_CodeSystem__system__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/ConceptMap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Concept Map
         * @description FHIR R4 `ConceptMap` across NAMASTE, TM2 and MMS.
         */
        get: operations["concept_map_api_v1_terminology_ConceptMap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/ValueSet/{system}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Value Set
         * @description FHIR R4 `ValueSet` enumerating one system's codes.
         */
        get: operations["value_set_api_v1_terminology_ValueSet__system__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminology/dual-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dual Codes
         * @description Every code equivalent to `code`, including itself.
         *
         *     Where nothing maps, the result holds only the source code. That is the
         *     correct answer, not an incomplete one.
         */
        get: operations["dual_codes_api_v1_terminology_dual_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ABHALinkRequest */
        ABHALinkRequest: {
            /** Abha Address */
            abha_address: string;
        };
        /** AcknowledgeRequest */
        AcknowledgeRequest: {
            /** Rule Id */
            rule_id: string;
            /** Note */
            note?: string | null;
        };
        /** AcknowledgeResponse */
        AcknowledgeResponse: {
            /** Intake Id */
            intake_id: string;
            /** Rule Id */
            rule_id: string;
            /** Acknowledged By */
            acknowledged_by: string;
            /**
             * Acknowledged At
             * Format: date-time
             */
            acknowledged_at: string;
        };
        /** Body_upload_document_api_v1_intakes__intake_id__documents_post */
        Body_upload_document_api_v1_intakes__intake_id__documents_post: {
            /** File */
            file: string;
            /** @default other */
            kind: components["schemas"]["DocumentKind"];
        };
        /** ConsentOut */
        ConsentOut: {
            /** Consent Id */
            consent_id: string;
            /** Intake Id */
            intake_id?: string | null;
            /** Consent Version */
            consent_version: string;
            /** Language */
            language: string;
            /** Notice Hash */
            notice_hash: string;
            /** Granted Purposes */
            granted_purposes?: string[];
            /** Refused Purposes */
            refused_purposes?: string[];
            /** Granting Party */
            granting_party: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Withdrawn At */
            withdrawn_at?: string | null;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /** Intake Id */
            intake_id?: string | null;
            /** Patient Id */
            patient_id?: string | null;
            /** Consent Version */
            consent_version: string;
            /** Language */
            language: string;
            /** Notice Text */
            notice_text: string;
            /** Granted Purposes */
            granted_purposes?: string[];
            /** Refused Purposes */
            refused_purposes?: string[];
            /**
             * Granting Party
             * @default self
             */
            granting_party: string;
            /** Granting Party Name */
            granting_party_name?: string | null;
            /** Audio Asset Id */
            audio_asset_id?: string | null;
        };
        /** ContradictionOut */
        ContradictionOut: {
            /** Field Id */
            field_id: string;
            /** Kind */
            kind: string;
            /** Reported Today */
            reported_today?: {
                [key: string]: unknown;
            } | null;
            /** From Record */
            from_record: {
                [key: string]: unknown;
            };
            /** Resolution */
            resolution: string;
        };
        /** DepartmentOut */
        DepartmentOut: {
            /** Code */
            code: string;
            /** Display */
            display: string;
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "prescription" | "lab_report" | "discharge_summary" | "other";
        /** DocumentOut */
        DocumentOut: {
            /** Document Id */
            document_id: string;
            kind: components["schemas"]["DocumentKind"];
            /** Status */
            status: string;
            /**
             * Page Count
             * @default 1
             */
            page_count: number;
            /** Confidence */
            confidence?: number | null;
            /**
             * Low Confidence
             * @default false
             */
            low_confidence: boolean;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Uploaded At */
            uploaded_at?: string | null;
            /** Processed At */
            processed_at?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * DocumentResultsRequest
         * @description An extraction the Jetson produced on-device.
         *
         *     The image stays on the device; only the structured result crosses the
         *     network. A hospital that will not let prescriptions leave the building gets
         *     the same report as one that will.
         */
        DocumentResultsRequest: {
            /** Extraction */
            extraction: {
                [key: string]: unknown;
            };
            /** @default other */
            kind: components["schemas"]["DocumentKind"];
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Url */
            url?: string | null;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** FactOut */
        FactOut: {
            /** Fact Id */
            fact_id: string;
            /** Field Id */
            field_id: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Value */
            value?: {
                [key: string]: unknown;
            } | null;
            /** Rendered */
            rendered?: string | null;
            /** Original Text */
            original_text?: string | null;
            /** Language */
            language?: string | null;
            /** Certainty */
            certainty: string;
            /** Channel */
            channel: string;
            /** Section */
            section: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Physician Verified
             * @default false
             */
            physician_verified: boolean;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
            /**
             * Needs Verification
             * @default false
             */
            needs_verification: boolean;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Ref */
            ref: {
                [key: string]: unknown;
            };
            /** Hospital Id */
            hospital_id: string;
            /** Intakes */
            intakes?: {
                [key: string]: unknown;
            }[];
            /** Carry Forward */
            carry_forward?: {
                [key: string]: unknown;
            }[];
            /** Scope Note */
            scope_note: string;
        };
        /** HospitalListResponse */
        HospitalListResponse: {
            /** Hospitals */
            hospitals?: components["schemas"]["HospitalOut"][];
        };
        /** HospitalOut */
        HospitalOut: {
            /** Hospital Id */
            hospital_id: string;
            /** Display Name */
            display_name: string;
            /** Location */
            location?: string | null;
            /** Timezone */
            timezone: string;
            /** Default Language */
            default_language: string;
            /** Departments */
            departments?: components["schemas"]["DepartmentOut"][];
        };
        /**
         * IngestResponse
         * @description What the kiosk gets back from `POST /intakes/ingest`.
         */
        IngestResponse: {
            /** Intake Id */
            intake_id: string;
            /** Status */
            status: string;
            /** Unresolved Fields */
            unresolved_fields?: string[];
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
            /**
             * Needs Manual Review
             * @default false
             */
            needs_manual_review: boolean;
            /** Red Flags */
            red_flags?: string[];
            /**
             * Contradictions
             * @default 0
             */
            contradictions: number;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** IntakeOut */
        IntakeOut: {
            /** Intake Id */
            intake_id: string;
            /** Hospital Id */
            hospital_id: string;
            /** Status */
            status: string;
            /** Language */
            language: string;
            /** Department Code */
            department_code?: string | null;
            /** Patient Ref */
            patient_ref: {
                [key: string]: unknown;
            };
            /** Facts */
            facts?: components["schemas"]["FactOut"][];
            /** Red Flags */
            red_flags?: components["schemas"]["RedFlagOut"][];
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
            /** Contradictions */
            contradictions?: components["schemas"]["ContradictionOut"][];
            /** Unresolved Fields */
            unresolved_fields?: string[];
            /**
             * Needs Review
             * @default false
             */
            needs_review: boolean;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /** Received At */
            received_at?: string | null;
            /** Seen At */
            seen_at?: string | null;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /**
         * MetricsOut
         * @description Operational counters worth stating out loud.
         *
         *     `repair_rate` is the one to watch: it should fall as the Jetson's extractor
         *     improves.
         */
        MetricsOut: {
            /**
             * Intakes
             * @default 0
             */
            intakes: number;
            /**
             * Repaired
             * @default 0
             */
            repaired: number;
            /**
             * Needs Manual Review
             * @default 0
             */
            needs_manual_review: number;
            /**
             * Repair Rate
             * @default 0
             */
            repair_rate: number;
        };
        /** OTPRequestBody */
        OTPRequestBody: {
            /** Phone */
            phone: string;
        };
        /** OTPRequestResponse */
        OTPRequestResponse: {
            /** Challenge Id */
            challenge_id: string;
            /** Expires At */
            expires_at: string;
            /** Code */
            code?: string | null;
            /** Delivery */
            delivery: string;
        };
        /** OTPVerifyBody */
        OTPVerifyBody: {
            /** Challenge Id */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /** PatientSessionResponse */
        PatientSessionResponse: {
            /** Token */
            token: string;
            /** Expires At */
            expires_at: string;
            /** Patient Ref */
            patient_ref: string;
        };
        /** RedFlagOut */
        RedFlagOut: {
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Label */
            label?: string | null;
            /** Fired At Turn */
            fired_at_turn?: number | null;
            /** Criteria Met */
            criteria_met?: string[];
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Acknowledged At */
            acknowledged_at?: string | null;
        };
        /**
         * ReportOut
         * @description The report, structured and rendered.
         *
         *     Both, always. The structure is what the dashboard links from; the text is
         *     what a physician reads, prints, or pastes into the HMIS when the integration
         *     is not there yet.
         */
        ReportOut: {
            /** Intake Id */
            intake_id: string;
            /** Language */
            language: string;
            /** Template Version */
            template_version: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Text */
            text: string;
            /** Physician Verified By */
            physician_verified_by?: string | null;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Type
             * @default guest
             */
            type: string;
            /** Value */
            value?: string | null;
        };
        /** ResolveResponse */
        ResolveResponse: {
            /** Ref */
            ref: {
                [key: string]: unknown;
            };
            /** Patient Id */
            patient_id?: string | null;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /**
             * Known Here
             * @default false
             */
            known_here: boolean;
            /** Source */
            source?: string | null;
            /** Notice */
            notice?: string | null;
        };
        /**
         * TerminologyMatchOut
         * @description One candidate. `mappings` is empty when no mapping exists — which is a
         *     real answer, not a gap for the client to fill in.
         */
        TerminologyMatchOut: {
            /** System */
            system: string;
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Score */
            score: number;
            /** Matched On */
            matched_on: string;
            /** Definition */
            definition?: string | null;
            /** Mappings */
            mappings?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** TerminologySearchOut */
        TerminologySearchOut: {
            /** Query */
            query: string;
            /** Systems */
            systems: string[];
            /** Results */
            results?: components["schemas"]["TerminologyMatchOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifyRequest
         * @description A physician confirming the record, or the fields they name.
         *
         *     Omitting `field_ids` verifies everything settled. Unsettled fields are
         *     skipped whatever is passed: there is nothing to confirm about a question
         *     that was never answered.
         */
        VerifyRequest: {
            /** Field Ids */
            field_ids?: string[] | null;
            /** Language */
            language?: string | null;
        };
        /** WorklistEntryOut */
        WorklistEntryOut: {
            /** Intake Id */
            intake_id: string;
            /** Department Code */
            department_code?: string | null;
            /** State */
            state: string;
            /** Intake Status */
            intake_status: string;
            /**
             * Arrived At
             * Format: date-time
             */
            arrived_at: string;
            /** Language */
            language: string;
            /**
             * Unacknowledged Alerts
             * @default 0
             */
            unacknowledged_alerts: number;
            /**
             * Unresolved Count
             * @default 0
             */
            unresolved_count: number;
            /**
             * Contradiction Count
             * @default 0
             */
            contradiction_count: number;
            /**
             * Needs Verification
             * @default false
             */
            needs_verification: boolean;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
            /**
             * Patient Ref Type
             * @default guest
             */
            patient_ref_type: string;
            /** Seen At */
            seen_at?: string | null;
        };
        /** WorklistOut */
        WorklistOut: {
            /** Department Code */
            department_code?: string | null;
            /** Entries */
            entries?: components["schemas"]["WorklistEntryOut"][];
            /** Pending Alerts */
            pending_alerts?: components["schemas"]["WorklistEntryOut"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    bundle_api_v1_content_bundle_get: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bundle_version_api_v1_content_bundle_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    consent_notice_api_v1_content_consent_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hospitals_api_v1_hospitals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalListResponse"];
                };
            };
        };
    };
    request_code_api_v1_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OTPRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerifyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_api_v1_auth_otp_sign_out_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_v1_intakes_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intake_api_v1_intakes__intake_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_intakes__intake_id__report_get: {
        parameters: {
            query?: {
                language?: string | null;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_intakes__intake_id__facts__fact_id__evidence_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_intakes__intake_id__verify_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_intakes__intake_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_intakes__intake_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_intakes__intake_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_results_api_v1_intakes__intake_id__documents_results_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_content_api_v1_documents_content__key__get: {
        parameters: {
            query?: {
                expires?: number | null;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_v1_patients_resolve_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_abha_api_v1_patients_me_abha_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ABHALinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_history_api_v1_patients_me_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_patients__ref__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    worklist_api_v1_worklist_get: {
        parameters: {
            query?: {
                department?: string | null;
                hours?: number;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_v1_alerts__intake_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_metrics_ingest_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_consent_api_v1_consent_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consent_api_v1_consent__consent_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_bundle_api_v1_fhir_intakes__intake_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_terminology_search_get: {
        parameters: {
            query: {
                q: string;
                systems?: string | null;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminologySearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    code_system_api_v1_terminology_CodeSystem__system__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                system: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    concept_map_api_v1_terminology_ConceptMap_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    value_set_api_v1_terminology_ValueSet__system__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path: {
                system: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dual_codes_api_v1_terminology_dual_codes_get: {
        parameters: {
            query: {
                system: string;
                code: string;
            };
            header?: {
                Authorization?: string | null;
                "X-User-Id"?: string | null;
                "X-User-Role"?: string | null;
                "X-Hospital-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
