/// The walker, against the bundle the backend actually compiles.
///
/// Every other walker test builds its own two-question fixture, which is right
/// for testing the walker's rules and wrong for testing whether it can walk the
/// real thing. This one loads `fixtures/questioning_bundle.json` — 92 questions
/// in nine languages, compiled from `clinical/questioning/` by
/// `questioning_agent/output/bundle.py` — and conducts interviews through it.
///
/// The fixture is regenerated by `backend/scripts/dump_bundle.py`, and a backend
/// test fails when it drifts from what the endpoint would serve. So a question
/// shape the compiler emits and this walker cannot read is caught here rather
/// than by a patient.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:medikiosk_app/content/answer.dart';
import 'package:medikiosk_app/content/bundle.dart';
import 'package:medikiosk_app/content/walker.dart';

ContentBundle load() {
  final file = File('test/fixtures/questioning_bundle.json');
  if (!file.existsSync()) {
    fail('missing ${file.path} — regenerate with backend/scripts/dump_bundle.py');
  }
  return ContentBundle.parse(file.readAsStringSync());
}

/// Answer whatever is on screen, by option code or value.
Answer reply(Question question, AnswerValue value, String text) => Answer(
      questionId: question.questionId,
      fieldId: question.fieldId,
      status: FieldStatus.answered,
      value: value,
      originalText: text,
      askedText: question.promptFor('en'),
      language: 'en',
    );

/// Walk to the question with [id], skipping everything before it.
///
/// Skips rather than inventing answers, so a test about reachability is not
/// accidentally a test of what a made-up answer does to the plan.
Question? walkTo(IntakeWalker walker, String id, {int limit = 200}) {
  for (var i = 0; i < limit; i++) {
    final question = walker.next();
    if (question == null) return null;
    if (question.questionId == id) return question;
    walker.record(Answer(
      questionId: question.questionId,
      fieldId: question.fieldId,
      status: FieldStatus.notAsked,
      language: 'en',
    ));
  }
  return null;
}

void main() {
  late ContentBundle bundle;
  setUpAll(() => bundle = load());

  group('the app can read what the backend compiles', () {
    test('the bundle is usable — format and record contract both known', () {
      expect(bundle.bundleFormat, '2');
      expect(bundle.isUsable, isTrue,
          reason: 'schema ${bundle.schemaVersion}, format ${bundle.bundleFormat}');
    });

    test('no question degrades to an answer type this build cannot render', () {
      // §4 lets an unknown type become `not_asked` rather than crash. None
      // should be taking that path against a current backend: every one of
      // them would be a question silently never put.
      final unknown = bundle.questions.values
          .where((q) => q.answerType == AnswerType.unknown)
          .map((q) => q.questionId);
      expect(unknown, isEmpty);
    });

    test('every question carries text in all nine languages', () {
      for (final language in bundle.languages) {
        final missing = bundle.questions.values
            .where((q) => q.promptFor(language) == null)
            .map((q) => q.questionId);
        expect(missing, isEmpty, reason: 'no $language text for $missing');
      }
    });
  });

  group('the fixed three, then what the patient actually reported', () {
    test('the interview opens with what is troubling you', () {
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      expect(first.questionId, 'fixed.complaints');
      expect(first.answerType, AnswerType.multiChoice);
      expect(first.options, contains('fever'));
    });

    test('which is worst offers back only what was ticked', () {
      // The engine fills these at runtime. Offering all fifteen again would be
      // asking somebody to re-read a list they have just finished reading.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(
          first, const CodedListValue(['fever', 'headache']), 'fever, headache'));

      final second = walker.next()!;
      expect(second.questionId, 'fixed.chief_complaint');
      expect(second.options, ['fever', 'headache']);
    });

    test('a domain the patient did not tick is never asked about', () {
      // §9: "how high did your temperature get" put to somebody who never
      // mentioned fever is a question that invents a symptom by asking it.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(first, const CodedListValue(['fever']), 'fever'));

      expect(walkTo(walker, 'fever.measured'), isNotNull,
          reason: 'fever was ticked, so its questions are reachable');

      final walker2 = IntakeWalker(bundle: bundle, language: 'en');
      final a = walker2.next()!;
      walker2.record(reply(a, const CodedListValue(['fever']), 'fever'));
      walkTo(walker2, '__exhaust__');
      expect(walker2.answers['respiratory.sputum_colour']?.status,
          FieldStatus.notApplicable,
          reason: 'not asked, and recorded as inapplicable rather than omitted');
    });

    test('ticking three problems asks about three', () {
      // The hand-authored bundle branched on the single chief complaint, so a
      // patient with fever and a cough was asked about one of them.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(
          first,
          const CodedListValue(['fever', 'respiratory', 'headache']),
          'fever, cough, headache'));

      for (final id in ['fever.measured', 'respiratory.cough_type', 'headache.site']) {
        final walker2 = IntakeWalker(bundle: bundle, language: 'en');
        final q = walker2.next()!;
        walker2.record(reply(
            q,
            const CodedListValue(['fever', 'respiratory', 'headache']),
            'three things'));
        expect(walkTo(walker2, id), isNotNull, reason: '\$id was unreachable');
      }
    });
  });

  group('the red-flag rules still fire', () {
    test('chest pain of sudden onset stops the interview', () {
      // The rule the whole interview exists to catch, and the one the compiler
      // first got wrong: `pain.site` is filled both by a coded question and by
      // a free-text description, and resolving onto the second made this rule
      // compare `chest` against a sentence.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(first, const CodedListValue(['pain']), 'pain'));

      // Onset first: the questions that apply to every domain are asked before
      // the ones specific to one, so a walk that answered the site first would
      // already have passed this.
      final onset = walkTo(walker, 'general.onset');
      expect(onset, isNotNull);
      walker.record(reply(onset!, const CodedValue('sudden'), 'suddenly'));

      final site = walkTo(walker, 'pain.site');
      expect(site, isNotNull, reason: 'the site question must be reachable');
      final outcome =
          walker.record(reply(site!, const CodedValue('chest'), 'chest'));

      expect(outcome, WalkOutcome.redFlag);
      expect(walker.firedFlag!.ruleId, 'chest_pain_sudden_onset');
      expect(walker.next(), isNull, reason: '§6: there is no path back in');
    });

    test('severe pain on the shared severity scale fires', () {
      // `general.severity` is asked once and stands for every active domain.
      // The rule is authored as `pain.severity >= 9`, which no question fills.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(first, const CodedListValue(['pain']), 'pain'));

      final severity = walkTo(walker, 'general.severity');
      expect(severity, isNotNull);
      final outcome =
          walker.record(reply(severity!, const NumberValue(9), '9'));

      expect(outcome, WalkOutcome.redFlag);
      expect(walker.firedFlag!.ruleId, 'severe_pain');
    });

    test('the same answers without the complaint do not fire', () {
      // Every rule is conjoined with membership of the fixed answer, so a
      // severity of 9 from somebody who never reported pain is not severe pain.
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      final first = walker.next()!;
      walker.record(reply(first, const CodedListValue(['sleep']), 'sleep'));

      final severity = walkTo(walker, 'general.severity');
      expect(severity, isNotNull);
      walker.record(reply(severity!, const NumberValue(9), '9'));
      expect(walker.firedFlag, isNull);
    });
  });

  group('the patient reads their own language', () {
    test('options carry content text, not a de-underscored code', () {
      final onset = bundle.questions['general.onset']!;
      expect(onset.labelForOption('sudden', 'en'), isNotNull);
      expect(onset.labelForOption('sudden', 'hi'), isNotNull);
      expect(onset.labelForOption('sudden', 'hi'),
          isNot(onset.labelForOption('sudden', 'en')),
          reason: 'Hindi that equals the English string is an untranslated string');
    });

    test('a Hindi interview is conducted in Hindi throughout', () {
      final walker = IntakeWalker(bundle: bundle, language: 'hi');
      final first = walker.next()!;
      expect(first.promptFor('hi'), isNotNull);
      expect(first.promptFor('hi'), isNot(first.promptFor('en')));
    });
  });

  group('a whole interview terminates', () {
    test('answering everything reaches the end without looping', () {
      final walker = IntakeWalker(bundle: bundle, language: 'en');
      var asked = 0;
      for (var i = 0; i < 300; i++) {
        final question = walker.next();
        if (question == null) break;
        asked++;
        walker.record(Answer(
          questionId: question.questionId,
          fieldId: question.fieldId,
          status: FieldStatus.unresolved,
          language: 'en',
        ));
      }
      expect(walker.next(), isNull, reason: 'the walk did not terminate');
      expect(asked, greaterThan(3));
    });

    test('a returning patient is asked the three current-state questions', () {
      // §5 screen 8 — agni, koshtha and nidra are what a Vaidya wants today's
      // answer to; the rest of the module does not move between two visits.
      final full = IntakeWalker(bundle: bundle, language: 'en').plan
          .where((id) => id.startsWith('ayush.'))
          .toSet();
      final returning =
          IntakeWalker(bundle: bundle, language: 'en', returnVisit: true)
              .plan
              .where((id) => id.startsWith('ayush.'))
              .toSet();
      expect(returning, isNotEmpty);
      expect(returning.length, lessThan(full.length));
      expect(returning, contains('ayush.appetite'));
    });
  });
}
