"""Templates and safety vocabulary for the physician summary.

The summary is assembled from facts by string templates, not generated. That is
the point: a template cannot hallucinate a symptom, and its output is valid on
its own. A language-compression provider may later rewrite this prose, but only
if every sentence it produces validates back against the same fact set — and the
template output stays the fallback.
"""

from __future__ import annotations

from collections.abc import Mapping

from app.domain.clinical.enums import Certainty, ReporterRole, Section

#: Section headings, in the order a clinician expects to read a history.
SECTION_TITLES: Mapping[Section, str] = {
    Section.CHIEF_COMPLAINT: "Chief complaint",
    Section.HPI: "History of presenting illness",
    Section.RED_FLAG_SCREEN: "Screening responses",
    Section.PAST_MEDICAL: "Past medical history",
    Section.PAST_SURGICAL: "Past surgical history",
    Section.MEDICATIONS: "Current medications",
    Section.ALLERGIES: "Allergies",
    Section.FAMILY_HISTORY: "Family history",
    Section.PERSONAL_HISTORY: "Personal history",
    Section.REVIEW_OF_SYSTEMS: "Review of systems",
    Section.AYURVEDA: "Ayurveda — patient-reported",
    Section.DOCUMENTS: "Prior investigations and documents",
    Section.IDENTITY: "Patient",
    Section.CONSENT: "Consent",
    Section.CONFIRMATION: "Patient confirmation",
}

#: Sections that appear in the rendered report, in render order.
REPORT_SECTIONS: tuple[Section, ...] = (
    Section.CHIEF_COMPLAINT,
    Section.HPI,
    Section.PAST_MEDICAL,
    Section.PAST_SURGICAL,
    Section.MEDICATIONS,
    Section.ALLERGIES,
    Section.FAMILY_HISTORY,
    Section.PERSONAL_HISTORY,
    Section.REVIEW_OF_SYSTEMS,
    Section.RED_FLAG_SCREEN,
    Section.DOCUMENTS,
    Section.AYURVEDA,
)

UNRESOLVED_TITLE = "Unresolved"
CONFLICTS_TITLE = "Information conflicts"
SAFETY_TITLE = "Safety"

#: Printed at the head of every report. It is not decoration: it is the sentence
#: that keeps a draft intake from being read as a clinical opinion.
HEADER_DISCLAIMER = (
    "DRAFT PRE-CONSULTATION INTAKE — patient-reported, not verified by a clinician. "
    "This document contains no diagnosis and no clinical advice."
)

FOOTER_DISCLAIMER = (
    "Generated by MediKiosk from patient-reported answers and uploaded documents. "
    "Every line requires physician verification before use."
)

NO_ALERTS_LINE = "No urgent clinical review criteria triggered."
NO_CONFLICTS_LINE = "No conflicts detected between today's answers and prior records."
NOTHING_RECORDED_LINE = "Nothing recorded."

#: How a fact's weaker provenance is annotated inline. A physician reading
#: "diabetes" needs to know at a glance whether the patient said it, the
#: attendant said it, or an OCR pass guessed it.
CERTAINTY_MARKERS: Mapping[Certainty, str] = {
    Certainty.CONFIRMED: "",
    Certainty.REPORTED: "",
    Certainty.APPROXIMATE: "approximate",
    Certainty.UNCERTAIN: "uncertain",
}

REPORTER_MARKERS: Mapping[ReporterRole, str] = {
    ReporterRole.SELF: "",
    ReporterRole.PARENT_GUARDIAN: "reported by parent/guardian",
    ReporterRole.FAMILY_ATTENDANT: "reported by attendant",
    ReporterRole.CAREGIVER: "reported by caregiver",
    ReporterRole.STAFF: "entered by staff",
}

#: Phrasing that turns something into clinical advice or an interpretation,
#: wherever it appears. Banned in prompts and in rendered output alike.
ADVICE_PATTERNS: tuple[str, ...] = (
    "you should take",
    "you must take",
    "you should stop",
    "we recommend",
    "i recommend",
    "you are advised",
    "prescribed for you",
    "treatment plan",
)

#: Phrasing that asserts an interpretation of the patient's findings. Also banned
#: everywhere: a kiosk that says "consistent with" has crossed the line whether
#: it said it in a question or in a report.
INTERPRETATION_PATTERNS: tuple[str, ...] = (
    "you are suffering",
    "diagnosis is",
    "you have been diagnosed",
    "likely due to",
    "probably due to",
    "consistent with",
    "suggestive of",
    "rule out",
    "in your case this means",
)

#: Named conditions and second-person assertions. Banned in *output* only.
#:
#: They cannot be banned in prompts, because a legitimate past-medical question
#: is "has a doctor ever told you that you have diabetes?" — the disease name and
#: the words "you have" are doing honest work there. In a generated report the
#: same phrases would be the system asserting a diagnosis, which it must never do.
FORBIDDEN_OUTPUT_PATTERNS: tuple[str, ...] = (
    "you have",
    "you are having",
    "diagnosed with",
    "myocardial infarction",
    "heart attack",
    "appendicitis",
    "stroke",
    "sepsis",
    "cancer",
)

#: What `find_unsupported_assertions` scans rendered output for. The evaluation
#: harness fails the build on any hit; the target is zero, always.
FORBIDDEN_ASSERTION_PATTERNS: tuple[str, ...] = (
    *FORBIDDEN_OUTPUT_PATTERNS,
    *ADVICE_PATTERNS,
    *INTERPRETATION_PATTERNS,
)

#: What prompts are scanned for. Narrower by design — see the note above.
FORBIDDEN_PROMPT_PATTERNS: tuple[str, ...] = (*ADVICE_PATTERNS, *INTERPRETATION_PATTERNS)


def _matches(text: str, patterns: tuple[str, ...]) -> tuple[str, ...]:
    lowered = text.lower()
    return tuple(p for p in patterns if p in lowered)


def find_unsupported_assertions(text: str) -> tuple[str, ...]:
    """Forbidden phrases present in generated output, in declaration order.

    Case-insensitive substring matching, deliberately blunt. A blunt check a
    content author cannot argue with is worth more here than a clever one.
    """
    return _matches(text, FORBIDDEN_ASSERTION_PATTERNS)


def find_prompt_violations(text: str) -> tuple[str, ...]:
    """Advice or interpretation in a question put to a patient.

    A question may name a disease — "has a doctor ever told you that you have
    diabetes?" is exactly the right way to take a past medical history. It may
    never give advice or offer an interpretation.
    """
    return _matches(text, FORBIDDEN_PROMPT_PATTERNS)


def annotate(certainty: Certainty, reporter: ReporterRole, verified: bool) -> str:
    """The bracketed qualifier appended to a summary line, or an empty string."""
    markers = [
        m
        for m in (CERTAINTY_MARKERS.get(certainty, ""), REPORTER_MARKERS.get(reporter, ""))
        if m
    ]
    if not verified:
        markers.append("unverified")
    return f" [{', '.join(markers)}]" if markers else ""
